'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {WerkZSimplePilotService,MemoryPilotRepository,FakeVoiceProvider,FakeMailProvider,FakeExtractor,DraftMailProvider,StaticMarketProvider,StaticPortfolioProvider}=require('../src/pilot');
class Auth{resolveSession(t){if(t==='a')return {organisationId:'org-a',actorId:'a',capabilities:['pilot.read','pilot.write']};if(t==='b')return {organisationId:'org-b',actorId:'b',capabilities:['pilot.read','pilot.write']};throw Object.assign(new Error('bad'),{code:'UNAUTHENTICATED'})}}
class Ent{require(org,m){if(!['werkz.simple','werkz.documents','werkz.billing-prep','werkz.channel.gmail','werkz.crypto-monitor'].includes(m))throw Object.assign(new Error('denied'),{code:'ENTITLEMENT_DENIED'});return {organisationId:org,moduleId:m}}}
function svc(){return new WerkZSimplePilotService({auth:new Auth(),entitlements:new Ent(),repository:new MemoryPilotRepository(),storage:{put:x=>({fileName:x.fileName,mime:x.mime,size:x.bytes.length})},voice:new FakeVoiceProvider(),mail:new FakeMailProvider(),extractor:new FakeExtractor(),outbound:new DraftMailProvider(),market:new StaticMarketProvider({source:'demo',live:false}),portfolio:new StaticPortfolioProvider({source:'demo',live:false}),clock:()=>new Date('2026-10-03T08:00:00Z')})}
test('tenant isolation and voice callback',async()=>{const s=svc();await s.recordCall('a',{providerPayload:{name:'Müller'}});assert.equal(s.listCalls('a').length,1);assert.equal(s.listCalls('b').length,0);assert.equal(s.summary('a').callbacks,1)});
test('monthly send requires explicit confirmation',async()=>{const s=svc();await s.addDocument('a',{fileName:'wieg.jpg',mime:'image/jpeg',dataBase64:Buffer.from('x').toString('base64')});const e=s.prepareExport('a','2026-10');await assert.rejects(()=>s.sendExport('a',{exportId:e.id,confirm:false,to:'tax@example.de'}),x=>x.code==='CONFIRMATION_REQUIRED');const sent=await s.sendExport('a',{exportId:e.id,confirm:true,to:'tax@example.de'});assert.equal(sent.delivery.mode,'draft')});
test('mail and crypto remain read only',async()=>{const s=svc(),mail=await s.relevantMail('a'),market=await s.marketSnapshot('a');assert.equal(mail.every(x=>x.mutatesMailbox===false),true);assert.equal(market.readOnly,true)});
test('public website inquiry becomes tenant-scoped callback',()=>{const s=svc();const created=s.publicInquiry('org-a',{name:'Kunde',phone:'05181 123',address:'Alfeld',reason:'Metallabholung',consent:true});assert.equal(created.received,true);const calls=s.listCalls('a');assert.equal(calls.length,1);assert.equal(calls[0].source,'website-contact');assert.equal(calls[0].location,'Alfeld');assert.equal(s.listCalls('b').length,0)});
test('public website inquiry requires consent and rejects honeypot',()=>{const s=svc();assert.throws(()=>s.publicInquiry('org-a',{name:'K',phone:'1',reason:'x',consent:false}),e=>e.code==='VALIDATION_ERROR');assert.throws(()=>s.publicInquiry('org-a',{name:'K',phone:'1',reason:'x',consent:true,company:'bot'}),e=>e.code==='SPAM_DENIED')});
