'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {WerkZSimplePilotService,MemoryPilotRepository,FakeVoiceProvider,FakeMailProvider,FakeExtractor,DraftMailProvider,StaticMarketProvider,StaticPortfolioProvider,StaticScrapPriceProvider}=require('../src/pilot');
class Auth{resolveSession(t){if(t==='a')return {organisationId:'org-a',actorId:'a',capabilities:['pilot.read','pilot.write']};if(t==='b')return {organisationId:'org-b',actorId:'b',capabilities:['pilot.read','pilot.write']};throw Object.assign(new Error('bad'),{code:'UNAUTHENTICATED'})}}
class Ent{require(org,m){if(!['werkz.simple','werkz.documents','werkz.billing-prep','werkz.channel.gmail','werkz.crypto-monitor'].includes(m))throw Object.assign(new Error('denied'),{code:'ENTITLEMENT_DENIED'});return {organisationId:org,moduleId:m}}}
function svc(){return new WerkZSimplePilotService({auth:new Auth(),entitlements:new Ent(),repository:new MemoryPilotRepository(),storage:{put:x=>({fileName:x.fileName,mime:x.mime,size:x.bytes.length})},voice:new FakeVoiceProvider(),mail:new FakeMailProvider(),extractor:new FakeExtractor(),outbound:new DraftMailProvider(),market:new StaticMarketProvider({source:'demo',live:false}),portfolio:new StaticPortfolioProvider({source:'demo',live:false}),scrapPrices:new StaticScrapPriceProvider({source:'demo',asOf:'2026-10-03T06:00:00Z',items:[{key:'mixed',label:'Mischschrott',unit:'EUR/t',price:210},{key:'grade-3',label:'Sorte 3',unit:'EUR/t',price:260,priceMin:250,priceMax:270},{key:'copper',label:'Kupfer',unit:'EUR/kg',price:9.92}]}),pickupDefaults:{vehicleCostPerKm:0.5,handlingCostEur:10,minimumProfitEur:50,targetMarginPct:15,vehiclePayloadKg:1200},clock:()=>new Date('2026-10-03T08:00:00Z')})}
test('tenant isolation and voice callback',async()=>{const s=svc();await s.recordCall('a',{providerPayload:{name:'Müller'}});assert.equal(s.listCalls('a').length,1);assert.equal(s.listCalls('b').length,0);assert.equal(s.summary('a').callbacks,1)});
test('monthly send requires explicit confirmation',async()=>{const s=svc();await s.addDocument('a',{fileName:'wieg.jpg',mime:'image/jpeg',dataBase64:Buffer.from('x').toString('base64')});const e=s.prepareExport('a','2026-10');await assert.rejects(()=>s.sendExport('a',{exportId:e.id,confirm:false,to:'tax@example.de'}),x=>x.code==='CONFIRMATION_REQUIRED');const sent=await s.sendExport('a',{exportId:e.id,confirm:true,to:'tax@example.de'});assert.equal(sent.delivery.mode,'draft')});
test('mail and crypto remain read only',async()=>{const s=svc(),mail=await s.relevantMail('a'),market=await s.marketSnapshot('a');assert.equal(mail.every(x=>x.mutatesMailbox===false),true);assert.equal(market.readOnly,true)});
test('public website inquiry becomes tenant-scoped callback',()=>{const s=svc();const created=s.publicInquiry('org-a',{name:'Kunde',phone:'05181 123',address:'Alfeld',reason:'Metallabholung',consent:true});assert.equal(created.received,true);const calls=s.listCalls('a');assert.equal(calls.length,1);assert.equal(calls[0].source,'website-contact');assert.equal(calls[0].category,'Abholung');assert.equal(calls[0].location,'Alfeld');assert.equal(s.listCalls('b').length,0)});
test('public website inquiry requires consent and rejects honeypot',()=>{const s=svc();assert.throws(()=>s.publicInquiry('org-a',{name:'K',phone:'1',reason:'x',consent:false}),e=>e.code==='VALIDATION_ERROR');assert.throws(()=>s.publicInquiry('org-a',{name:'K',phone:'1',reason:'x',consent:true,company:'bot'}),e=>e.code==='SPAM_DENIED')});

test('scrap prices keep ferrous in euro per tonne and non-ferrous in euro per kg',async()=>{const s=svc(),x=await s.scrapPriceSnapshot('a'),mixed=x.items.find(v=>v.key==='mixed'),copper=x.items.find(v=>v.key==='copper');assert.equal(mixed.displayUnit,'€/t');assert.equal(copper.displayUnit,'€/kg');assert.equal(mixed.price,210);assert.equal(copper.price,9.92)});


test('pickup profitability returns max customer payout and traffic-light decision',async()=>{const s=svc(),x=await s.pickupEstimate('a',{materialKey:'grade-3',weightKg:1000,distanceKm:10,customerPayoutEur:150});assert.equal(x.gross,260);assert.equal(x.driveCost,10);assert.equal(x.handlingCostEur,10);assert.equal(x.maxCustomerPayout,190);assert.equal(x.expectedProfit,90);assert.equal(x.decision,'lohnt');assert.equal(x.loadPct,83.33);assert.equal(s.listPickupEstimates('b').length,0)});

test('dealer settlements are tenant scoped and keep learned real prices',()=>{const s=svc();s.recordSettlement('a',{dealer:'Händler A',date:'2026-10-03',materialKey:'grade-3',materialLabel:'Sorte 3',weightKg:1000,totalEur:263,unit:'EUR/t'});s.recordSettlement('a',{dealer:'Händler A',date:'2026-10-04',materialKey:'grade-3',materialLabel:'Sorte 3',weightKg:1200,totalEur:324,unit:'EUR/t'});const insights=s.dealerInsights('a','grade-3');assert.equal(insights.length,1);assert.equal(insights[0].latestPrice,270);assert.equal(insights[0].averagePrice,266.5);assert.equal(insights[0].samples,2);assert.equal(s.listSettlements('b').length,0)});

test('route plan includes only open pickup calls for the tenant',async()=>{const s=svc();await s.recordCall('a',{name:'A',topic:'Metall abholen',location:'Ort A',estimatedWeightKg:500,distanceKm:12});await s.recordCall('b',{name:'B',topic:'Metall abholen',location:'Ort B',estimatedWeightKg:900,distanceKm:2});const plan=s.routePlan('a');assert.equal(plan.stops.length,1);assert.equal(plan.stops[0].location,'Ort A');assert.equal(plan.estimatedWeightKg,500)});


test('supermarket receipts default to private and stay out of tax export',async()=>{const s=svc();const d=await s.addDocument('a',{fileName:'rewe-bon.jpg',mime:'image/jpeg',dataBase64:Buffer.from('x').toString('base64')});assert.equal(d.type,'Kassenbon');assert.equal(d.company,'REWE');assert.equal(d.expenseClass,'privat');const e=s.prepareExport('a','2026-10');assert.equal(e.count,0);assert.equal(e.privateExcludedCount,1)});

test('private receipt can be moved to review when business items are marked',async()=>{const s=svc();const d=await s.addDocument('a',{fileName:'aldi-bon.jpg',mime:'image/jpeg',dataBase64:Buffer.from('x').toString('base64')});const changed=s.classifyDocument('a',{documentId:d.id,expenseClass:'pruefen',note:'Handschuhe markiert'});assert.equal(changed.expenseClass,'pruefen');const e=s.prepareExport('a','2026-10');assert.equal(e.count,1);assert.equal(e.reviewCount,1)});

test('wiegeschein is classified as business by default',async()=>{const s=svc();const d=await s.addDocument('a',{fileName:'wieg.jpg',mime:'image/jpeg',dataBase64:Buffer.from('x').toString('base64')});assert.equal(d.expenseClass,'betrieblich')});


test('explicit receipt buttons map to safe accounting classes',async()=>{const s=svc(),b64=Buffer.from('x').toString('base64');const priv=await s.addDocument('a',{fileName:'x.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'privat'});const fuel=await s.addDocument('a',{fileName:'x2.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'tanken'});const scrap=await s.addDocument('a',{fileName:'x3.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'schrottkauf'});const tool=await s.addDocument('a',{fileName:'x4.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'werkzeug'});const weigh=await s.addDocument('a',{fileName:'x5.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'wiegeschein'});const other=await s.addDocument('a',{fileName:'x6.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'sonstiges'});assert.equal(priv.expenseClass,'privat');assert.equal(fuel.expenseClass,'pruefen');assert.equal(scrap.expenseClass,'betrieblich');assert.equal(tool.expenseClass,'betrieblich');assert.equal(weigh.expenseClass,'betrieblich');assert.equal(other.expenseClass,'pruefen');assert.equal(scrap.receiptCategory,'schrottkauf')});
