'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {WerkZSimplePilotService,MemoryPilotRepository,PilotDocumentStorage,FakeVoiceProvider,FakeMailProvider,FakeExtractor,DraftMailProvider,StaticMarketProvider,StaticPortfolioProvider,StaticScrapPriceProvider}=require('../src/pilot');
class Auth{resolveSession(t){if(t==='a')return {organisationId:'org-a',organisationLabel:'Schrotti A',actorId:'a',actorLabel:'A',role:'owner',capabilities:['pilot.read','pilot.write']};if(t==='b')return {organisationId:'org-b',organisationLabel:'Schrotti B',actorId:'b',actorLabel:'B',role:'owner',capabilities:['pilot.read','pilot.write']};throw Object.assign(new Error('bad'),{code:'UNAUTHENTICATED'})}}
class Ent{isActive(org,m){return m==='werkz.crypto-monitor'}require(org,m){if(!['werkz.simple','werkz.documents','werkz.billing-prep','werkz.channel.gmail','werkz.crypto-monitor'].includes(m))throw Object.assign(new Error('denied'),{code:'ENTITLEMENT_DENIED'});return {organisationId:org,moduleId:m}}}
function svc(){return new WerkZSimplePilotService({auth:new Auth(),entitlements:new Ent(),repository:new MemoryPilotRepository(),storage:{put:x=>({fileName:x.fileName,mime:x.mime,size:x.bytes.length})},voice:new FakeVoiceProvider(),mail:new FakeMailProvider(),extractor:new FakeExtractor(),outbound:new DraftMailProvider(),market:new StaticMarketProvider({source:'demo',live:false}),portfolio:new StaticPortfolioProvider({source:'demo',live:false}),scrapPrices:new StaticScrapPriceProvider({source:'demo',asOf:'2026-10-03T06:00:00Z',items:[{key:'mixed',label:'Mischschrott',unit:'EUR/t',price:210},{key:'grade-3',label:'Sorte 3',unit:'EUR/t',price:260,priceMin:250,priceMax:270},{key:'copper',label:'Kupfer',unit:'EUR/kg',price:9.92}]}),pickupDefaults:{vehicleCostPerKm:0.5,handlingCostEur:10,minimumProfitEur:50,targetMarginPct:15,vehiclePayloadKg:1200},clock:()=>new Date('2026-10-03T08:00:00Z')})}
test('tenant isolation and voice callback',async()=>{const s=svc();await s.recordCall('a',{providerPayload:{name:'Müller'}});assert.equal(s.listCalls('a').length,1);assert.equal(s.listCalls('b').length,0);assert.equal(s.summary('a').callbacks,1)});
test('monthly send requires explicit confirmation',async()=>{const s=svc();await s.addDocument('a',{fileName:'wieg.jpg',mime:'image/jpeg',dataBase64:Buffer.from('x').toString('base64')});const e=s.prepareExport('a','2026-10');await assert.rejects(()=>s.sendExport('a',{exportId:e.id,confirm:false,to:'tax@example.de'}),x=>x.code==='CONFIRMATION_REQUIRED');const sent=await s.sendExport('a',{exportId:e.id,confirm:true,to:'tax@example.de'});assert.equal(sent.delivery.mode,'draft')});
test('mail and crypto remain read only',async()=>{const s=svc(),mail=await s.relevantMail('a'),market=await s.marketSnapshot('a');assert.equal(mail.every(x=>x.mutatesMailbox===false),true);assert.equal(market.readOnly,true)});
test('public website inquiry becomes tenant-scoped callback',()=>{const s=svc();const created=s.publicInquiry('org-a',{name:'Kunde',phone:'05181 123',address:'Alfeld',reason:'Metallabholung',consent:true});assert.equal(created.received,true);const calls=s.listCalls('a');assert.equal(calls.length,1);assert.equal(calls[0].source,'website-contact');assert.equal(calls[0].category,'Abholung');assert.equal(calls[0].location,'Alfeld');assert.equal(s.listCalls('b').length,0)});
test('public website inquiry requires consent and rejects honeypot',()=>{const s=svc();assert.throws(()=>s.publicInquiry('org-a',{name:'K',phone:'1',reason:'x',consent:false}),e=>e.code==='VALIDATION_ERROR');assert.throws(()=>s.publicInquiry('org-a',{name:'K',phone:'1',reason:'x',consent:true,company:'bot'}),e=>e.code==='SPAM_DENIED')});

test('scrap prices keep ferrous in euro per tonne and non-ferrous in euro per kg',async()=>{const s=svc(),x=await s.scrapPriceSnapshot('a'),mixed=x.items.find(v=>v.key==='mixed'),copper=x.items.find(v=>v.key==='copper');assert.equal(mixed.displayUnit,'€/t');assert.equal(copper.displayUnit,'€/kg');assert.equal(mixed.price,210);assert.equal(copper.price,9.92)});


test('pickup profitability returns max customer payout and traffic-light decision',async()=>{const s=svc(),x=await s.pickupEstimate('a',{materialKey:'grade-3',weightKg:1000,distanceKm:10,customerPayoutEur:150});assert.equal(x.gross,260);assert.equal(x.driveCost,10);assert.equal(x.handlingCostEur,10);assert.equal(x.maxCustomerPayout,190);assert.equal(x.expectedProfit,90);assert.equal(x.decision,'lohnt');assert.equal(x.loadPct,83.33);assert.equal(s.listPickupEstimates('b').length,0)});

test('dealer settlements are tenant scoped and keep learned real prices',()=>{const s=svc();s.recordSettlement('a',{dealer:'Händler A',date:'2026-10-03',materialKey:'grade-3',materialLabel:'Sorte 3',weightKg:1000,totalEur:263,unit:'EUR/t'});s.recordSettlement('a',{dealer:'Händler A',date:'2026-10-04',materialKey:'grade-3',materialLabel:'Sorte 3',weightKg:1200,totalEur:324,unit:'EUR/t'});const insights=s.dealerInsights('a','grade-3');assert.equal(insights.length,1);assert.equal(insights[0].latestPrice,270);assert.equal(insights[0].averagePrice,266.5);assert.equal(insights[0].samples,2);assert.equal(s.listSettlements('b').length,0)});

test('route plan includes only open pickup calls for the tenant',async()=>{const s=svc();await s.recordCall('a',{name:'A',topic:'Metall abholen',location:'Ort A',estimatedWeightKg:500,distanceKm:12});await s.recordCall('b',{name:'B',topic:'Metall abholen',location:'Ort B',estimatedWeightKg:900,distanceKm:2});const plan=s.routePlan('a');assert.equal(plan.stops.length,1);assert.equal(plan.stops[0].location,'Ort A');assert.equal(plan.estimatedWeightKg,500)});


test('unclassified merchant receipts require review before tax export',async()=>{const s=svc();const d=await s.addDocument('a',{fileName:'rewe-bon.jpg',mime:'image/jpeg',dataBase64:Buffer.from('x').toString('base64')});assert.equal(d.type,'Kassenbon');assert.equal(d.company,'REWE');assert.equal(d.expenseClass,'pruefen');const e=s.prepareExport('a','2026-10');assert.equal(e.count,1);assert.equal(e.reviewCount,1)});

test('merchant receipt can be explicitly classified by the user',async()=>{const s=svc();const d=await s.addDocument('a',{fileName:'aldi-bon.jpg',mime:'image/jpeg',dataBase64:Buffer.from('x').toString('base64')});const changed=s.classifyDocument('a',{documentId:d.id,expenseClass:'pruefen',note:'Handschuhe markiert'});assert.equal(changed.expenseClass,'pruefen');const e=s.prepareExport('a','2026-10');assert.equal(e.count,1);assert.equal(e.reviewCount,1)});


test('unknown merchant names are extracted dynamically without accounting claims',async()=>{const s=svc(),d=await s.addDocument('a',{fileName:'freierhandel-bon.jpg',mime:'image/jpeg',dataBase64:Buffer.from('x').toString('base64')});assert.equal(d.company,'FREIERHANDEL');assert.equal(d.expenseClass,'pruefen');assert.match(d.expenseReason,/prüfen/)});
test('wiegeschein is classified as business by default',async()=>{const s=svc();const d=await s.addDocument('a',{fileName:'wieg.jpg',mime:'image/jpeg',dataBase64:Buffer.from('x').toString('base64')});assert.equal(d.expenseClass,'betrieblich')});


test('explicit receipt buttons map to safe accounting classes',async()=>{const s=svc(),b64=Buffer.from('x').toString('base64');const priv=await s.addDocument('a',{fileName:'x.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'privat'});const fuel=await s.addDocument('a',{fileName:'x2.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'tanken'});const scrap=await s.addDocument('a',{fileName:'x3.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'schrottkauf'});const tool=await s.addDocument('a',{fileName:'x4.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'werkzeug'});const weigh=await s.addDocument('a',{fileName:'x5.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'wiegeschein'});const other=await s.addDocument('a',{fileName:'x6.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'sonstiges'});assert.equal(priv.expenseClass,'privat');assert.equal(fuel.expenseClass,'pruefen');assert.equal(scrap.expenseClass,'betrieblich');assert.equal(tool.expenseClass,'betrieblich');assert.equal(weigh.expenseClass,'betrieblich');assert.equal(other.expenseClass,'pruefen');assert.equal(scrap.receiptCategory,'schrottkauf')});


test('tax review can select subset and permanently delete wrong receipt',async()=>{const s=svc(),b64=Buffer.from('x').toString('base64');const a=await s.addDocument('a',{fileName:'a.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'schrottkauf'});const b=await s.addDocument('a',{fileName:'b.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'werkzeug'});const c=await s.addDocument('a',{fileName:'c.jpg',mime:'image/jpeg',dataBase64:b64,receiptCategory:'privat'});const ex=s.prepareExport('a','2026-10',[a.id]);assert.deepEqual(ex.documentIds,[a.id]);assert.equal(ex.count,1);assert.equal(ex.privateExcludedCount,1);assert.equal(ex.notSelectedCount,1);const del=s.deleteDocument('a',b.id);assert.equal(del.deleted,true);assert.equal(s.listDocuments('a').some(x=>x.id===b.id),false);assert.equal(s.listDocuments('b').length,0)});

test('deleting a document is tenant scoped',async()=>{const s=svc(),d=await s.addDocument('a',{fileName:'a.jpg',mime:'image/jpeg',dataBase64:Buffer.from('x').toString('base64'),receiptCategory:'sonstiges'});assert.throws(()=>s.deleteDocument('b',d.id),e=>e.code==='NOT_FOUND');assert.equal(s.listDocuments('a').length,1)});


test('voice note creates missing-receipt work item and uploaded receipt resolves it',async()=>{const s=svc(),n=s.addNote('a','Ich habe heute 800 kg Mischschrott geholt für 150 Euro');assert.equal(n.workItem.action,'abholung-erledigt');assert.equal(n.workItem.materialLabel,'Mischschrott');assert.equal(n.workItem.weightKg,800);assert.equal(n.workItem.spokenAmountEur,150);assert.equal(s.summary('a').missingDocuments,1);const d=await s.addDocument('a',{fileName:'schrott.jpg',mime:'image/jpeg',dataBase64:Buffer.from('receipt').toString('base64'),receiptCategory:'schrottkauf',workItemId:n.workItem.id});assert.equal(d.linkedWorkItemId,n.workItem.id);assert.equal(s.summary('a').missingDocuments,0)});

test('planned spoken pickup becomes a visible open task but not a missing receipt yet',()=>{const s=svc(),n=s.addNote('a','Ich muss morgen 800 kg Mischrott abholen');assert.equal(n.workItem.action,'abholung-geplant');assert.equal(n.workItem.documentExpected,false);assert.equal(n.workItem.materialLabel,'Mischschrott');assert.equal(s.summary('a').missingDocuments,0);const calls=s.listCalls('a');assert.equal(calls.length,1);assert.equal(calls[0].scheduledFor,'2026-10-04');assert.equal(calls[0].material,'Mischschrott');assert.equal(calls[0].category,'Abholung');const plan=s.routePlan('a');assert.equal(plan.stops.length,1);assert.equal(plan.stops[0].material,'Mischschrott');assert.equal(plan.stops[0].source,'voice-note')});

test('confirmed monthly handoff creates an archive record',async()=>{const s=svc();await s.addDocument('a',{fileName:'x.jpg',mime:'image/jpeg',dataBase64:Buffer.from('x').toString('base64'),receiptCategory:'werkzeug'});const e=s.prepareExport('a','2026-10'),sent=await s.sendExport('a',{exportId:e.id,confirm:true,to:'tax@example.de'});assert.equal(sent.archive.count,1);const archives=s.listExportArchives('a');assert.equal(archives.length,1);assert.equal(archives[0].month,'2026-10');assert.equal(s.listExportArchives('b').length,0)});

test('file archive preserves exact receipt bytes and hashes',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'werkz-pilot-'));try{const store=new PilotDocumentStorage(root),bytes=Buffer.from('exact receipt bytes'),stored=store.put({organisationId:'org-a',id:'doc-1',fileName:'beleg.jpg',mime:'image/jpeg',bytes}),exportRow={id:'export-1',month:'2026-10',documentIds:['doc-1'],totalAmount:42},doc={id:'doc-1',storage:stored,receiptCategory:'werkzeug',expenseClass:'betrieblich',company:'Test',date:'2026-10-03',amount:42,businessAmount:42},a=store.archiveExport({organisationId:'org-a',archiveId:'archive-1',exportRow,documents:[doc],delivery:{mode:'draft',accepted:false,to:'tax@example.de'},createdAt:'2026-10-03T08:00:00Z'}),manifest=store.readArchiveManifest({organisationId:'org-a',archiveId:'archive-1'}),copy=store.readArchiveFile({organisationId:'org-a',archiveId:'archive-1',fileName:manifest.files[0].fileName});assert.deepEqual(copy,bytes);assert.equal(manifest.files[0].sha256,stored.sha256);assert.equal(a.fileCount,1);assert.ok(a.manifestSha256)}finally{fs.rmSync(root,{recursive:true,force:true})}});


test('offline replay ids prevent duplicate notes and documents',async()=>{const s=svc(),id='offline-note-1',a=s.addNote('a','Ich muss morgen Mischschrott abholen',id),b=s.addNote('a','Ich muss morgen Mischschrott abholen',id);assert.equal(a.id,b.id);assert.equal(b.replayed,true);assert.equal(s.listWorkItems('a').length,1);assert.equal(s.listCalls('a').length,1);const body={fileName:'offline.jpg',mime:'image/jpeg',dataBase64:Buffer.from('x').toString('base64'),receiptCategory:'schrottkauf',clientMutationId:'offline-doc-1'},d1=await s.addDocument('a',body),d2=await s.addDocument('a',body);assert.equal(d1.id,d2.id);assert.equal(d2.replayed,true);assert.equal(s.listDocuments('a').filter(x=>x.clientMutationId==='offline-doc-1').length,1)});

test('simple pilot contains durable offline queue shell and compact sync dot',()=>{const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'apps/simple-pilot/index.html'),'utf8'),sw=fs.readFileSync(path.join(root,'apps/simple-pilot/sw.js'),'utf8'),manifest=JSON.parse(fs.readFileSync(path.join(root,'apps/simple-pilot/manifest.webmanifest'),'utf8')),server=fs.readFileSync(path.join(root,'tools/time-test-server.js'),'utf8');assert.match(html,/id="syncDot"/);assert.match(html,/indexedDB\.open\('werkz-simple-pilot',3\)/);assert.match(html,/window\.addEventListener\('online'/);assert.match(html,/queueablePost\('\/documents'/);assert.match(html,/serviceWorker\.register\('\/pilot\/sw\.js\?v=32',\{scope:'\/pilot\/',updateViaCache:'none'\}\)/);assert.equal(manifest.start_url,'/pilot/');assert.equal(manifest.scope,'/pilot/');assert.equal(manifest.name,'WERKZ – SCHROTTIES');assert.match(manifest.icons[0].src,/founder-point\.jpg/);assert.match(html,/apple-touch-icon/);assert.match(sw,/\/pilot\/api\//);assert.match(sw,/caches\.open\(CACHE\)/);assert.match(server,/\/pilot\/sw\.js/);assert.match(server,/manifest\.webmanifest/)});

test('backup state can restore tenant data and document bytes',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'werkz-backup-'));try{const auth=new Auth(),entitlements=new Ent(),repository=new MemoryPilotRepository(),storage=new PilotDocumentStorage(root),s=new WerkZSimplePilotService({auth,entitlements,repository,storage,voice:new FakeVoiceProvider(),mail:new FakeMailProvider(),extractor:new FakeExtractor(),outbound:new DraftMailProvider(),market:new StaticMarketProvider(),portfolio:new StaticPortfolioProvider(),scrapPrices:new StaticScrapPriceProvider({items:[]}),clock:()=>new Date('2026-10-03T08:00:00Z')});s.addNote('a','Ich muss morgen Mischschrott abholen');const d=await s.addDocument('a',{fileName:'bon.jpg',mime:'image/jpeg',dataBase64:Buffer.from('backup-bytes').toString('base64'),receiptCategory:'werkzeug'});const state=s.backupState('a');repository.replaceOrganisation('org-a','calls',[]);repository.replaceOrganisation('org-a','documents',[]);repository.replaceOrganisation('org-a','notes',[]);repository.replaceOrganisation('org-a','workItems',[]);assert.equal(s.summary('a').open,0);s.restoreState('a',{confirm:true,state});const restored=s.restoreDocument('a',{confirm:true,document:d,dataBase64:Buffer.from('backup-bytes').toString('base64')});assert.equal(restored.id,d.id);assert.equal(s.listCalls('a').length,1);assert.equal(s.listDocuments('a').length,1);assert.equal(storage.read({organisationId:'org-a',id:d.id,fileName:d.storage.fileName}).toString(),'backup-bytes');assert.equal(s.backupHealth('a').ok,true)}finally{fs.rmSync(root,{recursive:true,force:true})}});

test('backup restore is tenant scoped and requires confirmation',()=>{const s=svc(),state=s.backupState('a');assert.throws(()=>s.restoreState('a',{confirm:false,state}),e=>e.code==='CONFIRMATION_REQUIRED');s.restoreState('b',{confirm:true,state});assert.equal(s.listCalls('a').length,0);assert.equal(s.listCalls('b').length,0)});

test('simple pilot device backup uses indexeddb v3, local orders, server health and restore endpoints',()=>{const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'apps/simple-pilot/index.html'),'utf8'),server=fs.readFileSync(path.join(root,'tools/time-test-server.js'),'utf8');assert.match(html,/indexedDB\.open\('werkz-simple-pilot',3\)/);assert.match(html,/createObjectStore\('backup'/);assert.match(html,/createObjectStore\('files'/);assert.match(html,/createObjectStore\('localOrders'/);assert.match(html,/backupPilot\(\)/);assert.match(html,/restorePilot\(\)/);assert.match(html,/fetch\('\/healthz\?ts='/);assert.match(server,/storageWritable/);assert.match(server,/fs\.accessSync\(dataDir,fs\.constants\.W_OK\)/)});

test('completed pickup remembers customer, load, expense and missing receipt',async()=>{const s=svc();const call=await s.recordCall('a',{name:'Müller',phone:'05181 1',topic:'Metall abholen',location:'Alfeld',material:'Mischschrott',estimatedWeightKg:400});const done=s.completeCall('a',call.id,{boughtScrap:true,customerPayoutEur:75,receiptPresent:false,addToLoad:true,weightKg:420,materialKey:'mixed',materialLabel:'Mischschrott',clientMutationId:'done-1'});assert.equal(done.call.status,'erledigt');assert.equal(done.customer.name,'Müller');assert.equal(done.load.weightKg,420);assert.equal(done.cash.type,'ausgabe');assert.equal(done.cash.amount,75);assert.equal(done.workItem.status,'beleg-fehlt');assert.equal(s.listCustomers('a').length,1);assert.equal(s.listCashEntries('a').length,1);assert.equal(s.summary('a').missingDocuments,1);const replay=s.completeCall('a',call.id,{clientMutationId:'done-1'});assert.equal(replay.replayed,true);assert.equal(s.listCashEntries('a').length,1)});

test('vehicle load estimates value and payload',async()=>{const s=svc();s.addVehicleLoad('a',{materialKey:'grade-3',materialLabel:'Sorte 3',weightKg:600});s.addVehicleLoad('a',{materialKey:'copper',materialLabel:'Kupfer',weightKg:10});const x=await s.vehicleLoadSummary('a');assert.equal(x.totalWeightKg,610);assert.equal(x.loadPct,50.83);assert.equal(x.items.find(v=>v.materialKey==='grade-3').estimatedValueEur,156);assert.equal(x.items.find(v=>v.materialKey==='copper').estimatedValueEur,99.2)});

test('dealer options subtract learned roundtrip travel cost from current load',async()=>{const s=svc();s.addVehicleLoad('a',{materialKey:'grade-3',materialLabel:'Sorte 3',weightKg:1000});s.recordSettlement('a',{dealer:'Händler A',date:'2026-10-02',materialKey:'grade-3',materialLabel:'Sorte 3',weightKg:1000,totalEur:270,unit:'EUR/t',distanceKm:10});const rows=await s.dealerOptions('a');assert.equal(rows.length,1);assert.equal(rows[0].grossEur,270);assert.equal(rows[0].driveCostEur,10);assert.equal(rows[0].estimatedNetEur,260)});

test('cash notes and daily close keep private money separate',()=>{const s=svc();s.addCashEntry('a',{type:'ausgabe',amount:20,note:'Diesel'});s.addCashEntry('a',{type:'einnahme',amount:100,note:'Barverkauf'});s.addCashEntry('a',{type:'privat',amount:15,note:'Essen'});const d=s.dailySummary('a');assert.equal(d.expensesEur,20);assert.equal(d.incomeNotesEur,100);assert.equal(d.privateEur,15);assert.equal(d.knownResultEur,80)});

test('customer search finds customer material and dealer history',async()=>{const s=svc();s.saveCustomer('a',{name:'Müller',phone:'123',location:'Föhrste',material:'Kupfer'});s.recordSettlement('a',{dealer:'Recycling Nord',materialKey:'copper',materialLabel:'Kupfer',weightKg:10,totalEur:90,unit:'EUR/kg'});assert.equal(s.searchAll('a','föhrste').some(x=>x.type==='Kunde'),true);assert.equal(s.searchAll('a','recycling').some(x=>x.type==='Händlerpreis'),true);assert.equal(s.searchAll('b','müller').length,0)});

test('backup includes customers vehicle load and cash notes',()=>{const s=svc();s.saveCustomer('a',{name:'Kunde A'});s.addVehicleLoad('a',{materialKey:'mixed',materialLabel:'Mischschrott',weightKg:50});s.addCashEntry('a',{type:'privat',amount:5,note:'Essen'});const b=s.backupState('a');assert.equal(b.collections.customers.length,1);assert.equal(b.collections.vehicleLoad.length,1);assert.equal(b.collections.cashEntries.length,1)});

test('simple pilot exposes Schrotti daily workflow controls',()=>{const html=fs.readFileSync(path.join(__dirname,'../apps/simple-pilot/index.html'),'utf8');for(const id of ['loadMaterial','vehicleLoad','dealerOptionsBtn','dailySummary','cashSave','customers','globalSearch'])assert.match(html,new RegExp('id="'+id+'"'));assert.match(html,/AUFTRAG ERLEDIGT/);assert.match(html,/queueablePost\('\/vehicle-load'/);assert.match(html,/queueablePost\('\/cash'/);assert.match(html,/completeJob/)});

test('company tenants cannot see each other complete Schrotti data',async()=>{const s=svc();await s.recordCall('a',{name:'Kunde A',topic:'Schrott abholen',location:'Ort A',material:'Kupfer'});s.saveCustomer('a',{name:'Kunde A',location:'Ort A',material:'Kupfer'});s.addVehicleLoad('a',{materialKey:'copper',materialLabel:'Kupfer',weightKg:12});s.addCashEntry('a',{type:'ausgabe',amount:25,note:'Kauf A'});await s.addDocument('a',{fileName:'a.jpg',mime:'image/jpeg',dataBase64:Buffer.from('a').toString('base64'),receiptCategory:'schrottkauf'});s.recordSettlement('a',{dealer:'Händler A',materialKey:'copper',materialLabel:'Kupfer',weightKg:12,totalEur:100,unit:'EUR/kg'});assert.equal(s.listCalls('b').length,0);assert.equal(s.listCustomers('b').length,0);assert.equal((await s.vehicleLoadSummary('b')).totalWeightKg,0);assert.equal(s.listCashEntries('b').length,0);assert.equal(s.listDocuments('b').length,0);assert.equal(s.listSettlements('b').length,0);assert.equal(s.searchAll('b','Kupfer').length,0)});

test('session info exposes only active company identity',()=>{const s=svc(),a=s.sessionInfo('a'),b=s.sessionInfo('b');assert.deepEqual(a,{organisationId:'org-a',actorId:'a',actorLabel:'A',organisationLabel:'Schrotti A',publicSlug:null,role:'owner',voiceDiagnostics:false,modules:{cryptoMonitor:true}});assert.deepEqual(b,{organisationId:'org-b',actorId:'b',actorLabel:'B',organisationLabel:'Schrotti B',publicSlug:null,role:'owner',voiceDiagnostics:false,modules:{cryptoMonitor:true}})});

test('restoring one company backup does not alter another tenant',()=>{const s=svc();s.saveCustomer('a',{name:'A Kunde'});s.saveCustomer('b',{name:'B Kunde'});const state=s.backupState('a');s.restoreState('a',{confirm:true,state});assert.equal(s.listCustomers('a')[0].name,'A Kunde');assert.equal(s.listCustomers('b')[0].name,'B Kunde')});

test('pilot UI scopes offline queue cache and backups by company tenant',()=>{const html=fs.readFileSync(path.join(__dirname,'../apps/simple-pilot/index.html'),'utf8');assert.match(html,/tenantScope/);assert.match(html,/tenantKey\(key\)/);assert.match(html,/x\.tenant===tenantScope/);assert.match(html,/api\('\/session'\)/);assert.match(html,/werkzPilotTenantScope/);assert.match(html,/id="tenantName"/)});

test('test server supports configurable isolated pilot company tenants',()=>{const server=fs.readFileSync(path.join(__dirname,'../tools/time-test-server.js'),'utf8');assert.match(server,/WERKZ_PILOT_TENANTS_JSON/);assert.match(server,/organisationId:profile\.organisationId\|\|organisationId/);assert.match(server,/pilotOrganisationIds/);assert.match(server,/taxRecipientResolver/);assert.match(server,/publicOrganisationResolver/)});

test('owner portfolio snapshot needs separate organisation allowlist',async()=>{const marketProvider=new StaticMarketProvider({price:90000,actualHistory:[{valueEur:123}],live:true,source:'revolut-x'},['org-a']),portfolioProvider=new StaticPortfolioProvider({quantity:0.25,marketValueEur:22500,live:true,source:'revolut-x'},['org-a']);const market=await marketProvider.snapshot({organisationId:'org-a'}),portfolio=await portfolioProvider.portfolio({organisationId:'org-a'}),otherMarket=await marketProvider.snapshot({organisationId:'org-b'}),otherPortfolio=await portfolioProvider.portfolio({organisationId:'org-b'});assert.equal(market.live,false);assert.equal(portfolio.live,false);assert.equal(market.source,'owner-demo-snapshot');assert.equal(portfolio.source,'owner-demo-snapshot');assert.equal(portfolio.quantity,0.25);assert.equal(otherMarket.price,null);assert.equal(otherMarket.actualHistory,undefined);assert.equal(otherPortfolio.quantity,null);assert.equal(otherPortfolio.marketValueEur,null)});
test('crypto UI is entitlement gated and labels snapshot time',()=>{const html=fs.readFileSync(path.join(__dirname,'../apps/simple-pilot/index.html'),'utf8');assert.match(html,/id="marketSection"[^>]*hidden/);assert.match(html,/q\('#marketSection'\)\.hidden=!\(s\.modules&&s\.modules\.cryptoMonitor===true\)/);assert.match(html,/Beispiel: WerkZ-Eigentümer/);assert.match(html,/p\.source==='owner-demo-snapshot'/);assert.match(html,/Stand/);assert.doesNotMatch(html,/WerkZ Live-Demo/)});

test('completed pickup ignores later completion with a new mutation id',async()=>{const s=svc();const call=await s.recordCall('a',{name:'Müller',topic:'Metall abholen',estimatedWeightKg:420});const first=s.completeCall('a',call.id,{boughtScrap:true,customerPayoutEur:75,receiptPresent:false,addToLoad:true,weightKg:420,materialKey:'mixed',materialLabel:'Mischschrott',clientMutationId:'complete-first'});const second=s.completeCall('a',call.id,{boughtScrap:false,customerPayoutEur:0,receiptPresent:true,addToLoad:true,weightKg:900,clientMutationId:'complete-second'});assert.equal(second.replayed,true);assert.equal(second.call.id,first.call.id);assert.equal(second.call.customerPayoutEur,75);assert.equal(second.call.actualWeightKg,420);assert.equal(s.listCashEntries('a').length,1);assert.equal(s.listMissingDocuments('a').length,1);assert.equal((await s.vehicleLoadSummary('a')).totalWeightKg,420);assert.equal(s.listCalls('b').length,0)});

test('session exposes configured account emails only for its tenant',()=>{const s=svc(),resolve=s.auth.resolveSession.bind(s.auth);s.auth.resolveSession=token=>({...resolve(token),...(token==='a'?{accountEmails:['owner@example.invalid','backup@example.invalid']}: {})});assert.deepEqual(s.sessionInfo('a').accountEmails,['owner@example.invalid','backup@example.invalid']);assert.equal(s.sessionInfo('b').accountEmails,undefined)});

test('pilot test account name and emails come from runtime environment',()=>{const server=fs.readFileSync(path.join(__dirname,'../tools/time-test-server.js'),'utf8');assert.match(server,/WERKZ_PILOT_TEST_ACCOUNT_NAME/);assert.match(server,/WERKZ_PILOT_TEST_ACCOUNT_EMAILS/);assert.match(server,/accountEmails:profile\.accountEmails\|\|\[\]/);assert.doesNotMatch(server,/private-account-address-placeholder/)});
