'use strict';

const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');

const clone=value=>structuredClone(value);
const uid=prefix=>prefix+'_'+crypto.randomUUID();
function req(value,name){const v=String(value??'').trim();if(!v){const e=new Error(name+' required');e.code='VALIDATION_ERROR';throw e}return v}
function month(value){const v=req(value,'month');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(v)){const e=new Error('month invalid');e.code='VALIDATION_ERROR';throw e}return v}
function money(v){const n=Number(v);return Number.isFinite(n)?Math.round(n*100)/100:null}
function numeric(v,name,{min=0,max=Number.MAX_SAFE_INTEGER}={}){const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw Object.assign(new Error(name+' invalid'),{code:'VALIDATION_ERROR'});return n}
function scrapMid(item){const p=Number(item&&item.price),lo=Number(item&&item.priceMin),hi=Number(item&&item.priceMax);if(Number.isFinite(p))return p;if(Number.isFinite(lo)&&Number.isFinite(hi))return (lo+hi)/2;if(Number.isFinite(lo))return lo;if(Number.isFinite(hi))return hi;return null}
function scrapValue(item,weightKg,price){if(!Number.isFinite(price))return null;return item.unit==='EUR/t'?weightKg/1000*price:weightKg*price}
function classifyInquiry(value={}){const text=[value.topic,value.anliegen,value.reason,value.material].filter(Boolean).join(' ').toLowerCase();if(/abhol|abholung|abholen|container/.test(text))return 'Abholung';if(/angebot|preis|ankauf|verkauf|schrott|metall|kupfer|stahl|alu/.test(text))return 'Ankauf / Material';if(/termin/.test(text))return 'Termin';return 'Rückruf'}
function classifyExpense(ex={},input={}){const manual=String(input.expenseClass||'').toLowerCase();if(['betrieblich','privat','pruefen'].includes(manual))return {expenseClass:manual,expenseReason:'manuell gewählt'};const category=String(input.receiptCategory||'').toLowerCase(),categoryMap={privat:['privat','Kategorie: Privat'],tanken:['pruefen','Kategorie: Tanken – betriebliche Nutzung prüfen'],schrottkauf:['betrieblich','Kategorie: Schrottkauf'],werkzeug:['betrieblich','Kategorie: Werkzeug / Betrieb'],wiegeschein:['betrieblich','Kategorie: Wiegeschein / Verkauf'],sonstiges:['pruefen','Kategorie: Sonstiges']};if(categoryMap[category])return {expenseClass:categoryMap[category][0],expenseReason:categoryMap[category][1]};const type=String(ex.type||'').toLowerCase(),merchant=String(ex.company||ex.dealer||'').toLowerCase(),marked=input.businessMarked===true||ex.businessMarked===true||(Array.isArray(ex.highlightedBusinessItems)&&ex.highlightedBusinessItems.length>0);if(type.includes('wiegeschein'))return {expenseClass:'betrieblich',expenseReason:'Wiegeschein / Materialgeschäft'};if(/rewe|aldi|lidl|edeka|penny|netto|kaufland|norma|nahkauf/.test(merchant))return marked?{expenseClass:'pruefen',expenseReason:'Supermarktbon mit markiertem betrieblichem Posten'}:{expenseClass:'privat',expenseReason:'Supermarktbon ohne betriebliche Markierung'};if(/mrg|schrott|metall|recycling|wertstoff|hornbach|bauhaus|obi|hagebau|würth|wuerth|werkzeug|baustoff/.test(merchant))return {expenseClass:'betrieblich',expenseReason:'typischer Betriebs-/Materiallieferant'};if(/aral|shell|esso|total|jet|hem|tank/.test(merchant))return {expenseClass:'pruefen',expenseReason:'Tank-/Fahrtbeleg kann privat oder betrieblich sein'};return marked?{expenseClass:'pruefen',expenseReason:'betrieblicher Posten markiert'}:{expenseClass:'pruefen',expenseReason:'nicht eindeutig zuordenbar'}}

class VoiceProviderPort{async accept(){throw new Error('VoiceProviderPort.accept must be implemented')}}
class MailProviderPort{async listRelevant(){throw new Error('MailProviderPort.listRelevant must be implemented')}}
class DocumentExtractionPort{async extract(){throw new Error('DocumentExtractionPort.extract must be implemented')}}
class OutboundMailPort{async send(){throw new Error('OutboundMailPort.send must be implemented')}}
class MarketDataPort{async snapshot(){throw new Error('MarketDataPort.snapshot must be implemented')}}
class PortfolioReadPort{async portfolio(){throw new Error('PortfolioReadPort.portfolio must be implemented')}}
class ScrapPricePort{async snapshot(){throw new Error('ScrapPricePort.snapshot must be implemented')}}

class FilePilotRepository{
  constructor(file){this.file=path.resolve(file);this.state={calls:[],documents:[],notes:[],exports:[],pickupEstimates:[],settlements:[]};this.load()}
  load(){if(fs.existsSync(this.file)){const x=JSON.parse(fs.readFileSync(this.file,'utf8'));for(const k of Object.keys(this.state))if(!Array.isArray(x[k]))x[k]=[];this.state={...this.state,...x}}return this}
  save(){fs.mkdirSync(path.dirname(this.file),{recursive:true});const t=this.file+'.tmp';fs.writeFileSync(t,JSON.stringify(this.state,null,2));fs.renameSync(t,this.file)}
  list(org,key){this.load();return clone(this.state[key].filter(x=>x.organisationId===org))}
  add(key,row){this.load();this.state[key].push(clone(row));this.save();return clone(row)}
  update(org,key,id,patch){this.load();const i=this.state[key].findIndex(v=>v.organisationId===org&&v.id===id);if(i<0)return null;this.state[key][i]={...this.state[key][i],...clone(patch)};this.save();return clone(this.state[key][i])}
  remove(org,key,id){this.load();const i=this.state[key].findIndex(v=>v.organisationId===org&&v.id===id);if(i<0)return null;const [row]=this.state[key].splice(i,1);this.save();return clone(row)}
  removeWhere(org,key,field,value){this.load();const before=this.state[key].length;this.state[key]=this.state[key].filter(v=>!(v.organisationId===org&&v[field]===value));const removed=before-this.state[key].length;if(removed)this.save();return removed}
  find(org,key,id){this.load();const x=this.state[key].find(v=>v.organisationId===org&&v.id===id);return x?clone(x):null}
}
class MemoryPilotRepository{
  constructor(){this.state={calls:[],documents:[],notes:[],exports:[],pickupEstimates:[],settlements:[]}}
  list(org,key){return clone(this.state[key].filter(x=>x.organisationId===org))}
  add(key,row){this.state[key].push(clone(row));return clone(row)}
  update(org,key,id,patch){const i=this.state[key].findIndex(v=>v.organisationId===org&&v.id===id);if(i<0)return null;this.state[key][i]={...this.state[key][i],...clone(patch)};return clone(this.state[key][i])}
  remove(org,key,id){const i=this.state[key].findIndex(v=>v.organisationId===org&&v.id===id);if(i<0)return null;const [row]=this.state[key].splice(i,1);return clone(row)}
  removeWhere(org,key,field,value){const before=this.state[key].length;this.state[key]=this.state[key].filter(v=>!(v.organisationId===org&&v[field]===value));return before-this.state[key].length}
  find(org,key,id){const x=this.state[key].find(v=>v.organisationId===org&&v.id===id);return x?clone(x):null}
}
class PilotDocumentStorage{
  constructor(root){this.root=path.resolve(root)}
  put({organisationId,id,fileName,mime,bytes}){const safe=String(fileName||'beleg').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,120);const body=Buffer.from(bytes);if(body.length>12*1024*1024)throw Object.assign(new Error('too large'),{code:'PAYLOAD_TOO_LARGE'});const dir=path.join(this.root,organisationId,id);fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,safe);fs.writeFileSync(file,body);return {fileName:safe,mime,size:body.length,sha256:crypto.createHash('sha256').update(body).digest('hex'),objectKey:path.relative(this.root,file).split(path.sep).join('/')}}
  remove({organisationId,id}){const dir=path.join(this.root,organisationId,id);fs.rmSync(dir,{recursive:true,force:true});return true}
  read({organisationId,id,fileName}){const safe=String(fileName||'').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,120);const file=path.join(this.root,organisationId,id,safe);if(!fs.existsSync(file))throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});return fs.readFileSync(file)}
}

class FakeVoiceProvider extends VoiceProviderPort{
  async accept({payload={}}){return {name:payload.name||'Beispielkunde',phone:payload.phone||'',topic:payload.topic||'Rückruf wegen Metallabholung',location:payload.location||'Alfeld',material:payload.material||'Mischschrott',quantity:payload.quantity||'ca. 1 t',source:'voice-demo'}}
}
class FakeMailProvider extends MailProviderPort{
  async listRelevant(){const now=new Date().toISOString();return [
    {id:'mail-1',from:'kunde@example.de',subject:'Metall abholen',snippet:'Bitte um Rückruf wegen einer Abholung.',category:'Kundenanfrage',relevant:true,receivedAt:now},
    {id:'mail-2',from:'steuerberater@example.de',subject:'Unterlagen',snippet:'Bitte Monatsbelege bereitstellen.',category:'Steuerberater',relevant:true,receivedAt:now}
  ]}
}
class FakeExtractor extends DocumentExtractionPort{
  async extract({fileName}){const n=String(fileName||'').toLowerCase(),merchant=/rewe/.test(n)?'REWE':/aldi/.test(n)?'ALDI':/lidl/.test(n)?'LIDL':/edeka/.test(n)?'EDEKA':'';return {type:n.includes('wieg')?'Wiegeschein':(/bon|rewe|aldi|lidl|edeka/.test(n)?'Kassenbon':'Rechnung'),company:merchant,date:new Date().toISOString().slice(0,10),amount:null,weight:null,description:'Pilot: automatische Extraktion vorbereitet'}}
}
class DraftMailProvider extends OutboundMailPort{
  async send({to,subject,documents}){return {mode:'draft',accepted:false,to,subject,attachmentCount:documents.length,note:'Demo: vorbereitet, nicht extern versendet'}}
}
class StaticMarketProvider extends MarketDataPort{constructor(value=null){super();this.value=value}async snapshot(){return this.value||{source:'demo',live:false,symbol:'BTC/EUR',price:null,change24h:null,change30d:null,note:'Read-only Live-Verbindung ist vorbereitet.'}}}
class StaticPortfolioProvider extends PortfolioReadPort{constructor(value=null){super();this.value=value}async portfolio(){return this.value||{source:'demo',live:false,asset:'BTC',quantity:null,marketValueEur:null,costBasisEur:null,pnlEur:null,note:'Demo-Portfolio noch nicht serverseitig verbunden.'}}}
class StaticScrapPriceProvider extends ScrapPricePort{constructor(value=null){super();this.value=value}async snapshot(){return this.value||{source:'demo',asOf:null,items:[
  {key:'mixed-scrap',label:'Mischschrott',unit:'EUR/t',price:null},
  {key:'grade-3',label:'Sorte 3',unit:'EUR/t',price:null},
  {key:'shredder-feed',label:'Schreddervormaterial',unit:'EUR/t',price:null},
  {key:'copper',label:'Kupfer',unit:'EUR/kg',price:null},
  {key:'brass',label:'Messing',unit:'EUR/kg',price:null},
  {key:'lead',label:'Blei',unit:'EUR/kg',price:null},
  {key:'zinc',label:'Zink',unit:'EUR/kg',price:null},
  {key:'aluminium',label:'Aluminium',unit:'EUR/kg',price:null},
  {key:'cable',label:'Kabel',unit:'EUR/kg',price:null},
  {key:'motors',label:'Elektromotoren',unit:'EUR/t',price:null},
  {key:'batteries',label:'Bleibatterien',unit:'EUR/t',price:null},
  {key:'stainless-v2a',label:'V2A Edelstahl',unit:'EUR/t',price:null},
  {key:'stainless-v4a',label:'V4A Edelstahl',unit:'EUR/t',price:null}
],note:'Tagespreise / Richtwerte. Händlerpreis kann abweichen.'}}}

class WerkZSimplePilotService{
  constructor({auth,entitlements,repository,storage,voice,mail,extractor,outbound,market,portfolio,scrapPrices,pickupDefaults={},clock=()=>new Date(),audit=()=>{}}){Object.assign(this,{auth,entitlements,repository,storage,voice,mail,extractor,outbound,market,portfolio,scrapPrices,clock,audit});this.pickupDefaults={vehicleCostPerKm:0.45,handlingCostEur:15,minimumProfitEur:50,targetMarginPct:15,vehiclePayloadKg:1200,...pickupDefaults}}
  session(token,cap='pilot.read'){const s=this.auth.resolveSession(req(token,'session'));this.entitlements.require(s.organisationId,'werkz.simple');if(!s.capabilities.includes(cap)&&!s.capabilities.includes('pilot.admin'))throw Object.assign(new Error('forbidden'),{code:'FORBIDDEN'});return s}
  event(s,type,id,payload={}){this.audit({organisationId:s.organisationId,actorId:s.actorId,eventType:type,entityType:'pilot',entityId:id,source:'werkz.simple',payload})}
  summary(token){const s=this.session(token),calls=this.repository.list(s.organisationId,'calls'),docs=this.repository.list(s.organisationId,'documents');const m=this.clock().toISOString().slice(0,7);return {open:calls.filter(x=>x.status!=='erledigt').length,callbacks:calls.filter(x=>x.status==='neu'||x.status==='Rückruf').length,documentsThisMonth:docs.filter(x=>x.receivedAt.slice(0,7)===m).length}}
  async recordCall(token,input={}){const s=this.session(token,'pilot.write');const x=input.providerPayload?await this.voice.accept({payload:input.providerPayload}):input;const row=this.createInquiryRow(s.organisationId,x);this.repository.add('calls',row);this.event(s,'pilot.call.created',row.id,{source:row.source});return row}
  createInquiryRow(organisationId,x={}){return {id:uid('call'),organisationId:req(organisationId,'organisationId'),createdAt:this.clock().toISOString(),status:'neu',name:String(x.name||'Unbekannt').trim().slice(0,160),phone:String(x.phone||'').trim().slice(0,80),topic:String(x.topic||x.anliegen||'Rückruf').trim().slice(0,500),location:String(x.location||x.address||'').trim().slice(0,240),material:String(x.material||'').trim().slice(0,160),quantity:String(x.quantity||'').trim().slice(0,120),estimatedWeightKg:money(x.estimatedWeightKg),distanceKm:money(x.distanceKm),scheduledFor:x.scheduledFor||null,category:classifyInquiry(x),priority:'normal',source:x.source||'manual'}}
  publicInquiry(organisationId,input={}){if(input.company)throw Object.assign(new Error('spam denied'),{code:'SPAM_DENIED'});if(input.consent!==true)throw Object.assign(new Error('consent required'),{code:'VALIDATION_ERROR'});const clean={name:req(input.name,'name'),phone:req(input.phone,'phone'),topic:req(input.topic||input.reason,'topic'),location:String(input.location||input.address||'').trim(),material:String(input.material||'').trim(),quantity:String(input.quantity||'').trim(),source:'website-contact'};const row=this.createInquiryRow(organisationId,clean);this.repository.add('calls',row);this.audit({organisationId:row.organisationId,actorId:'public-website',eventType:'pilot.public-inquiry.created',entityType:'pilot',entityId:row.id,source:'werkz.simple',payload:{source:row.source}});return {id:row.id,status:row.status,received:true}}
  listCalls(token){const s=this.session(token);return this.repository.list(s.organisationId,'calls').sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
  addNote(token,text){const s=this.session(token,'pilot.write'),row={id:uid('note'),organisationId:s.organisationId,createdAt:this.clock().toISOString(),text:req(text,'text').slice(0,4000)};return this.repository.add('notes',row)}
  async addDocument(token,input){const s=this.session(token,'pilot.write');this.entitlements.require(s.organisationId,'werkz.documents');const bytes=Buffer.from(req(input.dataBase64,'dataBase64'),'base64'),id=uid('doc'),stored=this.storage.put({organisationId:s.organisationId,id,fileName:req(input.fileName,'fileName'),mime:req(input.mime,'mime'),bytes}),ex=await this.extractor.extract({fileName:input.fileName,mime:input.mime,bytes}),classification=classifyExpense(ex,input),row={id,organisationId:s.organisationId,receivedAt:this.clock().toISOString(),type:ex.type||'Sonstiges',company:ex.company||'',dealer:ex.dealer||ex.company||'',date:ex.date||null,amount:money(ex.amount),businessAmount:money(input.businessAmount??ex.businessAmount),receiptCategory:String(input.receiptCategory||'').toLowerCase()||null,expenseClass:classification.expenseClass,expenseReason:classification.expenseReason,weight:ex.weight??null,materialKey:ex.materialKey||'',material:ex.material||'',unit:ex.unit||null,unitPrice:money(ex.unitPrice),description:ex.description||'',storage:stored};this.repository.add('documents',row);if(row.type==='Wiegeschein'&&row.dealer&&row.material&&Number(row.weight)>0&&Number(row.amount)>0){this.addSettlementRow(s,{dealer:row.dealer,date:row.date||row.receivedAt.slice(0,10),materialKey:row.materialKey||row.material.toLowerCase().replace(/\s+/g,'-'),materialLabel:row.material,weightKg:Number(row.weight),totalEur:Number(row.amount),unit:row.unit||null,unitPrice:row.unitPrice,sourceDocumentId:id})}this.event(s,'pilot.document.created',id,{type:row.type,expenseClass:row.expenseClass});return row}
  classifyDocument(token,input={}){const s=this.session(token,'pilot.write'),id=req(input.documentId,'documentId'),expenseClass=req(input.expenseClass,'expenseClass').toLowerCase();if(!['betrieblich','privat','pruefen'].includes(expenseClass))throw Object.assign(new Error('expenseClass invalid'),{code:'VALIDATION_ERROR'});const patch={expenseClass,expenseReason:String(input.note||'manuell gewählt').slice(0,500)};if(input.businessAmount!=null)patch.businessAmount=money(input.businessAmount);const row=this.repository.update(s.organisationId,'documents',id,patch);if(!row)throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});this.event(s,'pilot.document.classified',id,{expenseClass});return row}
  listDocuments(token,m=null){const s=this.session(token),selected=m?month(m):null;return this.repository.list(s.organisationId,'documents').filter(x=>!selected||x.receivedAt.slice(0,7)===selected).sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt))}
  deleteDocument(token,id){const s=this.session(token,'pilot.write'),documentId=req(id,'documentId'),row=this.repository.find(s.organisationId,'documents',documentId);if(!row)throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});if(this.storage&&typeof this.storage.remove==='function')this.storage.remove({organisationId:s.organisationId,id:documentId,storage:row.storage});this.repository.removeWhere(s.organisationId,'settlements','sourceDocumentId',documentId);this.repository.remove(s.organisationId,'documents',documentId);this.event(s,'pilot.document.deleted',documentId,{type:row.type,receiptCategory:row.receiptCategory||null});return {deleted:true,id:documentId}}
  documentFile(token,id){const s=this.session(token),documentId=req(id,'documentId'),row=this.repository.find(s.organisationId,'documents',documentId);if(!row)throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});if(!this.storage||typeof this.storage.read!=='function')throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});return {mime:row.storage&&row.storage.mime||'application/octet-stream',fileName:row.storage&&row.storage.fileName||'beleg',bytes:this.storage.read({organisationId:s.organisationId,id:documentId,fileName:row.storage&&row.storage.fileName})}}

  async pickupEstimate(token,input={}){const s=this.session(token,'pilot.write'),snap=await this.scrapPrices.snapshot({organisationId:s.organisationId}),items=Array.isArray(snap.items)?snap.items:[],materialKey=req(input.materialKey,'materialKey'),item=items.find(x=>x.key===materialKey);if(!item)throw Object.assign(new Error('material not found'),{code:'NOT_FOUND'});const weightKg=numeric(input.weightKg,'weightKg',{min:1,max:100000}),oneWayKm=numeric(input.distanceKm??0,'distanceKm',{min:0,max:2000}),roundTripKm=input.roundTripKm!=null?numeric(input.roundTripKm,'roundTripKm',{min:0,max:4000}):oneWayKm*2,vehicleCostPerKm=numeric(input.vehicleCostPerKm??this.pickupDefaults.vehicleCostPerKm,'vehicleCostPerKm',{min:0,max:10}),handlingCostEur=numeric(input.handlingCostEur??this.pickupDefaults.handlingCostEur,'handlingCostEur',{min:0,max:10000}),minimumProfitEur=numeric(input.minimumProfitEur??this.pickupDefaults.minimumProfitEur,'minimumProfitEur',{min:0,max:100000}),targetMarginPct=numeric(input.targetMarginPct??this.pickupDefaults.targetMarginPct,'targetMarginPct',{min:0,max:95}),payloadKg=numeric(input.vehiclePayloadKg??this.pickupDefaults.vehiclePayloadKg,'vehiclePayloadKg',{min:1,max:100000});const price=scrapMid(item);if(!Number.isFinite(price))throw Object.assign(new Error('price unavailable'),{code:'VALIDATION_ERROR'});const lo=Number.isFinite(Number(item.priceMin))?Number(item.priceMin):price,hi=Number.isFinite(Number(item.priceMax))?Number(item.priceMax):price,gross=money(scrapValue(item,weightKg,price)),grossLow=money(scrapValue(item,weightKg,lo)),grossHigh=money(scrapValue(item,weightKg,hi)),driveCost=money(roundTripKm*vehicleCostPerKm),netBeforePurchase=money(gross-driveCost-handlingCostEur),targetProfit=money(Math.max(minimumProfitEur,gross*targetMarginPct/100)),maxCustomerPayout=money(Math.max(0,netBeforePurchase-targetProfit)),customerPayout=input.customerPayoutEur==null?null:numeric(input.customerPayoutEur,'customerPayoutEur',{min:0,max:1000000}),expectedProfit=customerPayout==null?null:money(netBeforePurchase-customerPayout),decision=expectedProfit==null?(maxCustomerPayout>0?'lohnt':'knapp'):(expectedProfit>=targetProfit?'lohnt':expectedProfit>=0?'knapp':'nicht-lohnend'),row={id:uid('pickup'),organisationId:s.organisationId,createdAt:this.clock().toISOString(),materialKey,materialLabel:item.label,weightKg,price,displayUnit:item.unit==='EUR/t'?'€/t':'€/kg',gross,grossLow,grossHigh,distanceKm:oneWayKm,roundTripKm,vehicleCostPerKm,driveCost,handlingCostEur,targetProfit,maxCustomerPayout,customerPayoutEur:customerPayout,expectedProfit,vehiclePayloadKg:payloadKg,loadPct:money(weightKg/payloadKg*100),decision,priceSource:snap.source||'Richtwert',priceAsOf:snap.asOf||null};this.repository.add('pickupEstimates',row);this.event(s,'pilot.pickup.estimated',row.id,{materialKey,decision});return row}
  listPickupEstimates(token){const s=this.session(token);return this.repository.list(s.organisationId,'pickupEstimates').sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
  addSettlementRow(s,input={}){const unit=input.unit==='EUR/t'||input.unit==='EUR/kg'?input.unit:(Number(input.weightKg)>=100?'EUR/t':'EUR/kg'),weightKg=numeric(input.weightKg,'weightKg',{min:0.01,max:1000000}),totalEur=numeric(input.totalEur,'totalEur',{min:0,max:10000000}),derived=unit==='EUR/t'?totalEur/(weightKg/1000):totalEur/weightKg,row={id:uid('settlement'),organisationId:s.organisationId,createdAt:this.clock().toISOString(),date:String(input.date||this.clock().toISOString().slice(0,10)),dealer:req(input.dealer,'dealer').slice(0,160),materialKey:req(input.materialKey,'materialKey').slice(0,120),materialLabel:String(input.materialLabel||input.materialKey).slice(0,160),weightKg:money(weightKg),totalEur:money(totalEur),unit,unitPrice:money(input.unitPrice??derived),sourceDocumentId:input.sourceDocumentId||null,distanceKm:money(input.distanceKm)};this.repository.add('settlements',row);return row}
  recordSettlement(token,input={}){const s=this.session(token,'pilot.write'),row=this.addSettlementRow(s,input);this.event(s,'pilot.settlement.created',row.id,{dealer:row.dealer,materialKey:row.materialKey});return row}
  listSettlements(token){const s=this.session(token);return this.repository.list(s.organisationId,'settlements').sort((a,b)=>(b.date+b.createdAt).localeCompare(a.date+a.createdAt))}
  dealerInsights(token,materialKey=null){const s=this.session(token),rows=this.repository.list(s.organisationId,'settlements').filter(x=>!materialKey||x.materialKey===materialKey),groups=new Map();for(const row of rows){const key=row.dealer+'|'+row.materialKey;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)}return [...groups.values()].map(list=>{list.sort((a,b)=>(b.date+b.createdAt).localeCompare(a.date+a.createdAt));const latest=list[0],avg=money(list.reduce((n,x)=>n+Number(x.unitPrice||0),0)/list.length);return {dealer:latest.dealer,materialKey:latest.materialKey,materialLabel:latest.materialLabel,unit:latest.unit,latestPrice:latest.unitPrice,latestDate:latest.date,averagePrice:avg,samples:list.length}}).sort((a,b)=>Number(b.latestPrice)-Number(a.latestPrice))}
  routePlan(token){const s=this.session(token),calls=this.repository.list(s.organisationId,'calls').filter(x=>x.category==='Abholung'&&x.status!=='erledigt').sort((a,b)=>(Number(a.distanceKm)||9999)-(Number(b.distanceKm)||9999)||a.createdAt.localeCompare(b.createdAt));return {stops:calls.map(x=>({id:x.id,name:x.name,location:x.location,material:x.material,quantity:x.quantity,estimatedWeightKg:x.estimatedWeightKg,distanceKm:x.distanceKm,phone:x.phone,scheduledFor:x.scheduledFor})),estimatedWeightKg:money(calls.reduce((n,x)=>n+(Number(x.estimatedWeightKg)||0),0)),note:'Reihenfolge nutzt bekannte Entfernungen; echte Routenoptimierung braucht einen Karten-/Distanzanbieter.'}}
  async relevantMail(token){const s=this.session(token);this.entitlements.require(s.organisationId,'werkz.channel.gmail');return (await this.mail.listRelevant({organisationId:s.organisationId})).filter(x=>x.relevant!==false).map(x=>({...x,mutatesMailbox:false}))}
  prepareExport(token,m,selectedDocumentIds=null){const s=this.session(token,'pilot.write');this.entitlements.require(s.organisationId,'werkz.billing-prep');const selected=month(m),all=this.repository.list(s.organisationId,'documents').filter(x=>x.receivedAt.slice(0,7)===selected),requested=Array.isArray(selectedDocumentIds)?new Set(selectedDocumentIds.map(String)):null,docs=all.filter(x=>x.expenseClass!=='privat'&&(!requested||requested.has(x.id))),row={id:uid('export'),organisationId:s.organisationId,month:selected,createdAt:this.clock().toISOString(),status:'prepared',documentIds:docs.map(x=>x.id),count:docs.length,availableCount:all.length,privateExcludedCount:all.filter(x=>x.expenseClass==='privat').length,notSelectedCount:all.filter(x=>x.expenseClass!=='privat'&&requested&&!requested.has(x.id)).length,reviewCount:docs.filter(x=>x.expenseClass==='pruefen').length,totalAmount:Math.round(docs.reduce((n,x)=>n+(Number.isFinite(Number(x.businessAmount))?Number(x.businessAmount):(x.expenseClass==='betrieblich'?(Number(x.amount)||0):0)),0)*100)/100};return this.repository.add('exports',row)}
  async sendExport(token,{exportId,confirm,to}){const s=this.session(token,'pilot.write');if(confirm!==true)throw Object.assign(new Error('confirmation required'),{code:'CONFIRMATION_REQUIRED'});const row=this.repository.find(s.organisationId,'exports',req(exportId,'exportId'));if(!row)throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});const docs=this.repository.list(s.organisationId,'documents').filter(x=>row.documentIds.includes(x.id));const delivery=await this.outbound.send({organisationId:s.organisationId,to:req(to,'to'),subject:'Unterlagen '+row.month,text:'WerkZ Monatsübergabe',documents:docs});return {...row,delivery}}
  async marketSnapshot(token){const s=this.session(token);this.entitlements.require(s.organisationId,'werkz.crypto-monitor');const [market,portfolio]=await Promise.all([this.market.snapshot({organisationId:s.organisationId}),this.portfolio.portfolio({organisationId:s.organisationId})]);return {label:'Demo-Portfolio',readOnly:true,market,portfolio,generatedAt:this.clock().toISOString()}}
  async scrapPriceSnapshot(token){const s=this.session(token);const snap=await this.scrapPrices.snapshot({organisationId:s.organisationId});return {...snap,items:Array.isArray(snap.items)?snap.items.map(x=>({...x,displayUnit:x.unit==='EUR/t'?'€/t':'€/kg'})):[],generatedAt:this.clock().toISOString()}}
}

function cookieValue(cookie,name){const x=String(cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='));return x?decodeURIComponent(x.slice(name.length+1)):null}
function sendJson(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(data))}
async function readBody(reqr,limit=14*1024*1024){const chunks=[];let size=0;for await(const c of reqr){size+=c.length;if(size>limit)throw Object.assign(new Error('too large'),{code:'PAYLOAD_TOO_LARGE'});chunks.push(c)}const raw=Buffer.concat(chunks).toString('utf8');return raw?JSON.parse(raw):{}}
function status(error){return {UNAUTHENTICATED:401,FORBIDDEN:403,ENTITLEMENT_DENIED:403,NOT_FOUND:404,CONFIRMATION_REQUIRED:409,PAYLOAD_TOO_LARGE:413,VALIDATION_ERROR:400,SPAM_DENIED:400,RATE_LIMITED:429}[error.code]||500}
function createPilotHttpHandler({service,defaultTaxRecipient='steuerberater@example.invalid',publicOrganisationId='org-device-test'}){
  const recentPublic=new Map();
  function allowPublic(request){const ip=String(request.headers['x-forwarded-for']||request.socket?.remoteAddress||'unknown').split(',')[0].trim();const now=Date.now(),windowMs=10*60*1000,limit=8;const values=(recentPublic.get(ip)||[]).filter(x=>now-x<windowMs);if(values.length>=limit)throw Object.assign(new Error('rate limited'),{code:'RATE_LIMITED'});values.push(now);recentPublic.set(ip,values)}
  return async function(reqr,res){const url=new URL(reqr.url,'http://werkz.invalid');if(!url.pathname.startsWith('/pilot/api/')&&!url.pathname.startsWith('/pilot/public/'))return false;const token=cookieValue(reqr.headers.cookie,'werkz_session');try{
    if(reqr.method==='POST'&&url.pathname==='/pilot/public/contact'){allowPublic(reqr);const body=await readBody(reqr,64*1024);sendJson(res,201,service.publicInquiry(publicOrganisationId,body));return true;}
    if(reqr.method==='GET'&&url.pathname==='/pilot/api/summary')sendJson(res,200,service.summary(token));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/calls')sendJson(res,200,service.listCalls(token));
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/calls')sendJson(res,201,await service.recordCall(token,await readBody(reqr)));
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/notes'){const b=await readBody(reqr);sendJson(res,201,service.addNote(token,b.text))}
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/documents')sendJson(res,201,await service.addDocument(token,await readBody(reqr)));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/documents')sendJson(res,200,service.listDocuments(token,url.searchParams.get('month')||null));
    else if(reqr.method==='GET'&&url.pathname.startsWith('/pilot/api/documents/')&&url.pathname.endsWith('/file')){const id=decodeURIComponent(url.pathname.slice('/pilot/api/documents/'.length,-'/file'.length));const file=service.documentFile(token,id);res.writeHead(200,{'content-type':file.mime,'content-disposition':'inline; filename="'+String(file.fileName).replace(/"/g,'')+'"','cache-control':'private, max-age=60','x-content-type-options':'nosniff'});res.end(file.bytes)}
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/documents/classify')sendJson(res,200,service.classifyDocument(token,await readBody(reqr)));
    else if(reqr.method==='DELETE'&&url.pathname.startsWith('/pilot/api/documents/'))sendJson(res,200,service.deleteDocument(token,decodeURIComponent(url.pathname.slice('/pilot/api/documents/'.length))));
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/pickup-estimates')sendJson(res,201,await service.pickupEstimate(token,await readBody(reqr)));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/pickup-estimates')sendJson(res,200,service.listPickupEstimates(token));
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/settlements')sendJson(res,201,service.recordSettlement(token,await readBody(reqr)));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/settlements')sendJson(res,200,service.listSettlements(token));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/dealer-insights')sendJson(res,200,service.dealerInsights(token,url.searchParams.get('material')||null));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/route-plan')sendJson(res,200,service.routePlan(token));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/mail')sendJson(res,200,await service.relevantMail(token));
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/export/prepare'){const b=await readBody(reqr);sendJson(res,201,service.prepareExport(token,b.month,b.selectedDocumentIds))}
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/export/send'){const b=await readBody(reqr);sendJson(res,200,await service.sendExport(token,{...b,to:b.to||defaultTaxRecipient}))}
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/market')sendJson(res,200,await service.marketSnapshot(token));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/scrap-prices')sendJson(res,200,await service.scrapPriceSnapshot(token));
    else sendJson(res,404,{error:'NOT_FOUND'});
    return true
  }catch(e){sendJson(res,status(e),{error:e.code||'ERROR',message:e.code==='VALIDATION_ERROR'?e.message:'Request failed'});return true}}
}

function parseSnapshot(value){if(!value)return {};try{const x=JSON.parse(value);return x&&typeof x==='object'?x:{}}catch{return {}}}
function createPilotRuntime({auth,entitlements,dataDir,audit=()=>{}}){const snap=parseSnapshot(process.env.WERKZ_DEMO_CRYPTO_SNAPSHOT),scrap=parseSnapshot(process.env.WERKZ_SCRAP_PRICE_SNAPSHOT),pickupDefaults=parseSnapshot(process.env.WERKZ_PICKUP_DEFAULTS);return new WerkZSimplePilotService({auth,entitlements,repository:new FilePilotRepository(path.join(dataDir,'pilot.json')),storage:new PilotDocumentStorage(path.join(dataDir,'documents')),voice:new FakeVoiceProvider(),mail:new FakeMailProvider(),extractor:new FakeExtractor(),outbound:new DraftMailProvider(),market:new StaticMarketProvider(snap.market||null),portfolio:new StaticPortfolioProvider(snap.portfolio||null),scrapPrices:new StaticScrapPriceProvider(scrap.items?scrap:null),pickupDefaults,audit})}

module.exports={VoiceProviderPort,MailProviderPort,DocumentExtractionPort,OutboundMailPort,MarketDataPort,PortfolioReadPort,ScrapPricePort,FilePilotRepository,MemoryPilotRepository,PilotDocumentStorage,FakeVoiceProvider,FakeMailProvider,FakeExtractor,DraftMailProvider,StaticMarketProvider,StaticPortfolioProvider,StaticScrapPriceProvider,WerkZSimplePilotService,createPilotHttpHandler,createPilotRuntime,parseSnapshot,classifyInquiry,classifyExpense};
