'use strict';

const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');

const clone=value=>structuredClone(value);
const uid=prefix=>prefix+'_'+crypto.randomUUID();
function req(value,name){const v=String(value??'').trim();if(!v){const e=new Error(name+' required');e.code='VALIDATION_ERROR';throw e}return v}
function month(value){const v=req(value,'month');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(v)){const e=new Error('month invalid');e.code='VALIDATION_ERROR';throw e}return v}
function money(v){const n=Number(v);return Number.isFinite(n)?Math.round(n*100)/100:null}
function numeric(v,name,{min=0,max=Number.MAX_SAFE_INTEGER}={}){const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw Object.assign(new Error(name+' invalid'),{code:'VALIDATION_ERROR'});return n}
function scrapMid(item){const p=Number(item&&item.price),lo=Number(item&&item.priceMin),hi=Number(item&&item.priceMax);if(Number.isFinite(p))return p;if(Number.isFinite(lo)&&Number.isFinite(hi))return (lo+hi)/2;if(Number.isFinite(lo))return lo;if(Number.isFinite(hi))return hi;return null}
function scrapValue(item,weightKg,price){if(!Number.isFinite(price))return null;return item.unit==='EUR/t'?weightKg/1000*price:weightKg*price}
function classifyInquiry(value={}){const text=[value.topic,value.anliegen,value.reason,value.material].filter(Boolean).join(' ').toLowerCase();if(/abhol|abholung|abholen|container/.test(text))return 'Abholung';if(/angebot|preis|ankauf|verkauf|schrott|metall|kupfer|stahl|alu/.test(text))return 'Ankauf / Material';if(/termin/.test(text))return 'Termin';return 'Rückruf'}
function classifyExpense(ex={},input={}){const manual=String(input.expenseClass||'').toLowerCase();if(['betrieblich','privat','pruefen'].includes(manual))return {expenseClass:manual,expenseReason:'manuell gewählt'};const category=String(input.receiptCategory||'').toLowerCase(),categoryMap={privat:['privat','Kategorie: Privat'],tanken:['pruefen','Kategorie: Tanken – betriebliche Nutzung prüfen'],schrottkauf:['betrieblich','Kategorie: Schrottkauf'],werkzeug:['betrieblich','Kategorie: Werkzeug / Betrieb'],wiegeschein:['betrieblich','Kategorie: Wiegeschein / Verkauf'],sonstiges:['pruefen','Kategorie: Sonstiges']};if(categoryMap[category])return {expenseClass:categoryMap[category][0],expenseReason:categoryMap[category][1]};const type=String(ex.type||'').toLowerCase(),merchant=String(ex.company||ex.dealer||'').toLowerCase(),marked=input.businessMarked===true||ex.businessMarked===true||(Array.isArray(ex.highlightedBusinessItems)&&ex.highlightedBusinessItems.length>0);if(type.includes('wiegeschein'))return {expenseClass:'betrieblich',expenseReason:'Wiegeschein / Materialgeschäft'};if(/rewe|aldi|lidl|edeka|penny|netto|kaufland|norma|nahkauf/.test(merchant))return marked?{expenseClass:'pruefen',expenseReason:'Supermarktbon mit markiertem betrieblichem Posten'}:{expenseClass:'privat',expenseReason:'Supermarktbon ohne betriebliche Markierung'};if(/mrg|schrott|metall|recycling|wertstoff|hornbach|bauhaus|obi|hagebau|würth|wuerth|werkzeug|baustoff/.test(merchant))return {expenseClass:'betrieblich',expenseReason:'typischer Betriebs-/Materiallieferant'};if(/aral|shell|esso|total|jet|hem|tank/.test(merchant))return {expenseClass:'pruefen',expenseReason:'Tank-/Fahrtbeleg kann privat oder betrieblich sein'};return marked?{expenseClass:'pruefen',expenseReason:'betrieblicher Posten markiert'}:{expenseClass:'pruefen',expenseReason:'nicht eindeutig zuordenbar'}}
function noteMaterial(text=''){const t=String(text).toLowerCase(),map=[
  ['grade-3','Sorte 3',/sorte\s*3|schwer(?:er|en)?\s+(?:stahl|schrott)/],
  ['mixed-scrap','Mischschrott',/misch(?:s?ch?rott|rot)|mischrott/],
  ['aluminium','Aluminium',/\balu(?:minium)?\b/],
  ['copper','Kupfer',/kupfer/],
  ['brass','Messing',/messing/],
  ['cable','Kabel',/kabel/],
  ['motors','Elektromotoren',/elektromotor|\bmotoren?\b/],
  ['batteries','Bleibatterien',/batterie|akku/],
  ['stainless-v4a','V4A',/\bv\s*4\s*a\b/],
  ['stainless-v2a','V2A',/\bv\s*2\s*a\b/],
  ['zinc','Zink',/zink|dachrinn/],
  ['lead','Blei',/\bblei\b/]
];for(const [key,label,re] of map)if(re.test(t))return {key,label};return {key:null,label:''}}
function noteNumber(raw){return Number(String(raw||'').replace(/\./g,'').replace(',','.'))}
function noteWeightKg(text=''){const m=String(text).match(/(\d+(?:[.,]\d+)?)\s*(kg|kilo(?:gramm)?|t|tonne[n]?)/i);if(!m)return null;const n=noteNumber(m[1]);return Number.isFinite(n)?money(/^(t|tonne)/i.test(m[2])?n*1000:n):null}
function noteAmountEur(text=''){const s=String(text),m=s.match(/(?:für|bezahlt|bekommen|erhalten|preis)?\s*(\d+(?:[.,]\d+)?)\s*(?:€|eur|euro)/i);if(!m)return null;const n=noteNumber(m[1]);return Number.isFinite(n)?money(n):null}
function noteDate(text='',now=new Date()){const t=String(text).toLowerCase(),base=new Date(now);base.setHours(12,0,0,0);if(/übermorgen/.test(t)){base.setDate(base.getDate()+2);return base.toISOString().slice(0,10)}if(/morgen/.test(t)){base.setDate(base.getDate()+1);return base.toISOString().slice(0,10)}if(/heute/.test(t))return base.toISOString().slice(0,10);const m=t.match(/\b(\d{1,2})\.(\d{1,2})\.(?:(\d{2,4}))?\b/);if(m){let y=m[3]?Number(m[3]):base.getFullYear();if(y<100)y+=2000;const d=new Date(Date.UTC(y,Number(m[2])-1,Number(m[1]),12));if(Number.isFinite(d.getTime()))return d.toISOString().slice(0,10)}return null}
function parseOperationalNote(text,now=new Date()){const raw=req(text,'text').slice(0,4000),t=raw.toLowerCase(),material=noteMaterial(t),weightKg=noteWeightKg(t),amountEur=noteAmountEur(t),date=noteDate(t,now),dealer=/\bmrg\b/.test(t)?'MRG':'',planned=/(?:soll|muss|werde|will|möchte|moechte|noch|kann).{0,60}(?:abholen|holen|einsammeln|mitnehmen)|(?:abholen|holen|einsammeln|mitnehmen).{0,40}(?:morgen|übermorgen|heute|am\s+\d|nächste|naechste)/.test(t),sold=/verkauft|abgegeben|angeliefert|(?:zu|bei)\s+mrg\s+(?:gebracht|gefahren)|zum\s+händler\s+gebracht/.test(t),fuel=/getankt|tanken|tankstelle/.test(t),tool=/werkzeug|handschuh|schraub|trennscheib|bohrer|maschine/.test(t)&&/gekauft|geholt|bezahlt/.test(t),bought=/(?:schrott|metall|kupfer|messing|alu|minium|kabel|motor|batterie|v2a|v4a).{0,40}(?:gekauft|bezahlt)|(?:gekauft|bezahlt).{0,40}(?:schrott|metall|kupfer|messing|alu|minium|kabel|motor|batterie|v2a|v4a)/.test(t),collected=/\b(?:habe|hab|heute)?\s*(?:abgeholt|geholt|eingesammelt)\b/.test(t)&&!planned;let action='notiz',expectedCategory=null,documentExpected=false,completed=false;if(planned){action='abholung-geplant';expectedCategory='schrottkauf'}else if(sold){action='verkauf';expectedCategory='wiegeschein';documentExpected=true;completed=true}else if(fuel){action='tanken';expectedCategory='tanken';documentExpected=true;completed=true}else if(tool){action='werkzeugkauf';expectedCategory='werkzeug';documentExpected=true;completed=true}else if(bought||collected){action=bought?'schrottkauf':'abholung-erledigt';expectedCategory='schrottkauf';documentExpected=true;completed=true}return {action,materialKey:material.key,materialLabel:material.label,weightKg,amountEur,date,dealer,expectedCategory,documentExpected,completed,raw}}
function sameDayOrNear(a,b){if(!a||!b)return true;const da=new Date(a+'T12:00:00Z'),db=new Date(b+'T12:00:00Z');return Number.isFinite(da.getTime())&&Number.isFinite(db.getTime())?Math.abs(da-db)<=3*86400000:true}


class VoiceProviderPort{async accept(){throw new Error('VoiceProviderPort.accept must be implemented')}}
class MailProviderPort{async listRelevant(){throw new Error('MailProviderPort.listRelevant must be implemented')}}
class DocumentExtractionPort{async extract(){throw new Error('DocumentExtractionPort.extract must be implemented')}}
class OutboundMailPort{async send(){throw new Error('OutboundMailPort.send must be implemented')}}
class MarketDataPort{async snapshot(){throw new Error('MarketDataPort.snapshot must be implemented')}}
class PortfolioReadPort{async portfolio(){throw new Error('PortfolioReadPort.portfolio must be implemented')}}
class ScrapPricePort{async snapshot(){throw new Error('ScrapPricePort.snapshot must be implemented')}}

class FilePilotRepository{
  constructor(file){this.file=path.resolve(file);this.state={calls:[],documents:[],notes:[],exports:[],pickupEstimates:[],settlements:[],workItems:[],archives:[]};this.load()}
  load(){if(fs.existsSync(this.file)){const x=JSON.parse(fs.readFileSync(this.file,'utf8'));for(const k of Object.keys(this.state))if(!Array.isArray(x[k]))x[k]=[];this.state={...this.state,...x}}return this}
  save(){fs.mkdirSync(path.dirname(this.file),{recursive:true});const t=this.file+'.tmp';fs.writeFileSync(t,JSON.stringify(this.state,null,2));fs.renameSync(t,this.file)}
  list(org,key){this.load();return clone(this.state[key].filter(x=>x.organisationId===org))}
  add(key,row){this.load();this.state[key].push(clone(row));this.save();return clone(row)}
  update(org,key,id,patch){this.load();const i=this.state[key].findIndex(v=>v.organisationId===org&&v.id===id);if(i<0)return null;this.state[key][i]={...this.state[key][i],...clone(patch)};this.save();return clone(this.state[key][i])}
  remove(org,key,id){this.load();const i=this.state[key].findIndex(v=>v.organisationId===org&&v.id===id);if(i<0)return null;const [row]=this.state[key].splice(i,1);this.save();return clone(row)}
  removeWhere(org,key,field,value){this.load();const before=this.state[key].length;this.state[key]=this.state[key].filter(v=>!(v.organisationId===org&&v[field]===value));const removed=before-this.state[key].length;if(removed)this.save();return removed}
  find(org,key,id){this.load();const x=this.state[key].find(v=>v.organisationId===org&&v.id===id);return x?clone(x):null}
}
class MemoryPilotRepository{
  constructor(){this.state={calls:[],documents:[],notes:[],exports:[],pickupEstimates:[],settlements:[],workItems:[],archives:[]}}
  list(org,key){return clone(this.state[key].filter(x=>x.organisationId===org))}
  add(key,row){this.state[key].push(clone(row));return clone(row)}
  update(org,key,id,patch){const i=this.state[key].findIndex(v=>v.organisationId===org&&v.id===id);if(i<0)return null;this.state[key][i]={...this.state[key][i],...clone(patch)};return clone(this.state[key][i])}
  remove(org,key,id){const i=this.state[key].findIndex(v=>v.organisationId===org&&v.id===id);if(i<0)return null;const [row]=this.state[key].splice(i,1);return clone(row)}
  removeWhere(org,key,field,value){const before=this.state[key].length;this.state[key]=this.state[key].filter(v=>!(v.organisationId===org&&v[field]===value));return before-this.state[key].length}
  find(org,key,id){const x=this.state[key].find(v=>v.organisationId===org&&v.id===id);return x?clone(x):null}
}
class PilotDocumentStorage{
  constructor(root){this.root=path.resolve(root)}
  put({organisationId,id,fileName,mime,bytes}){const safe=String(fileName||'beleg').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,120);const body=Buffer.from(bytes);if(body.length>12*1024*1024)throw Object.assign(new Error('too large'),{code:'PAYLOAD_TOO_LARGE'});const dir=path.join(this.root,organisationId,id);fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,safe);fs.writeFileSync(file,body);return {fileName:safe,mime,size:body.length,sha256:crypto.createHash('sha256').update(body).digest('hex'),objectKey:path.relative(this.root,file).split(path.sep).join('/')}}
  remove({organisationId,id}){const dir=path.join(this.root,organisationId,id);fs.rmSync(dir,{recursive:true,force:true});return true}
  read({organisationId,id,fileName}){const safe=String(fileName||'').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,120);const file=path.join(this.root,organisationId,id,safe);if(!fs.existsSync(file))throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});return fs.readFileSync(file)}
  archiveExport({organisationId,archiveId,exportRow,documents,delivery,createdAt}){const dir=path.join(this.root,'_exports',organisationId,archiveId);if(fs.existsSync(dir))throw Object.assign(new Error('archive exists'),{code:'STATE_INVALID'});fs.mkdirSync(dir,{recursive:true});const files=[];documents.forEach((doc,index)=>{const original=this.read({organisationId,id:doc.id,fileName:doc.storage&&doc.storage.fileName}),safe=String(doc.storage&&doc.storage.fileName||'beleg').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,100),name=String(index+1).padStart(3,'0')+'-'+doc.id+'-'+safe,target=path.join(dir,name);fs.writeFileSync(target,original,{flag:'wx'});files.push({documentId:doc.id,fileName:name,originalFileName:doc.storage&&doc.storage.fileName||safe,mime:doc.storage&&doc.storage.mime||'application/octet-stream',size:original.length,sha256:crypto.createHash('sha256').update(original).digest('hex'),receiptCategory:doc.receiptCategory||null,expenseClass:doc.expenseClass||null,company:doc.company||'',date:doc.date||null,amount:doc.amount??null,businessAmount:doc.businessAmount??null})});const manifest={archiveId,organisationId,exportId:exportRow.id,month:exportRow.month,createdAt,documentIds:exportRow.documentIds.slice(),count:files.length,totalAmount:exportRow.totalAmount,delivery:{mode:delivery&&delivery.mode||null,accepted:delivery&&delivery.accepted===true,to:delivery&&delivery.to||null},files};const body=Buffer.from(JSON.stringify(manifest,null,2));fs.writeFileSync(path.join(dir,'manifest.json'),body,{flag:'wx'});return {archiveId,objectKey:path.relative(this.root,dir).split(path.sep).join('/'),manifestSha256:crypto.createHash('sha256').update(body).digest('hex'),fileCount:files.length}}
  readArchiveManifest({organisationId,archiveId}){const file=path.join(this.root,'_exports',organisationId,archiveId,'manifest.json');if(!fs.existsSync(file))throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});return JSON.parse(fs.readFileSync(file,'utf8'))}
  readArchiveFile({organisationId,archiveId,fileName}){const safe=path.basename(String(fileName||''));const file=path.join(this.root,'_exports',organisationId,archiveId,safe);if(!fs.existsSync(file)||safe==='manifest.json')throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});return fs.readFileSync(file)}
}

class FakeVoiceProvider extends VoiceProviderPort{
  async accept({payload={}}){return {name:payload.name||'Beispielkunde',phone:payload.phone||'',topic:payload.topic||'Rückruf wegen Metallabholung',location:payload.location||'Alfeld',material:payload.material||'Mischschrott',quantity:payload.quantity||'ca. 1 t',source:'voice-demo'}}
}
class FakeMailProvider extends MailProviderPort{
  async listRelevant(){const now=new Date().toISOString();return [
    {id:'mail-1',from:'kunde@example.de',subject:'Metall abholen',snippet:'Bitte um Rückruf wegen einer Abholung.',category:'Kundenanfrage',relevant:true,receivedAt:now},
    {id:'mail-2',from:'steuerberater@example.de',subject:'Unterlagen',snippet:'Bitte Monatsbelege bereitstellen.',category:'Steuerberater',relevant:true,receivedAt:now}
  ]}
}
class FakeExtractor extends DocumentExtractionPort{
  async extract({fileName}){const n=String(fileName||'').toLowerCase(),merchant=/rewe/.test(n)?'REWE':/aldi/.test(n)?'ALDI':/lidl/.test(n)?'LIDL':/edeka/.test(n)?'EDEKA':'';return {type:n.includes('wieg')?'Wiegeschein':(/bon|rewe|aldi|lidl|edeka/.test(n)?'Kassenbon':'Rechnung'),company:merchant,date:new Date().toISOString().slice(0,10),amount:null,weight:null,description:'Pilot: automatische Extraktion vorbereitet'}}
}
class DraftMailProvider extends OutboundMailPort{
  async send({to,subject,documents}){return {mode:'draft',accepted:false,to,subject,attachmentCount:documents.length,note:'Demo: vorbereitet, nicht extern versendet'}}
}
class StaticMarketProvider extends MarketDataPort{constructor(value=null){super();this.value=value}async snapshot(){return this.value||{source:'demo',live:false,symbol:'BTC/EUR',price:null,change24h:null,change30d:null,note:'Read-only Live-Verbindung ist vorbereitet.'}}}
class StaticPortfolioProvider extends PortfolioReadPort{constructor(value=null){super();this.value=value}async portfolio(){return this.value||{source:'demo',live:false,asset:'BTC',quantity:null,marketValueEur:null,costBasisEur:null,pnlEur:null,note:'Demo-Portfolio noch nicht serverseitig verbunden.'}}}
class StaticScrapPriceProvider extends ScrapPricePort{constructor(value=null){super();this.value=value}async snapshot(){return this.value||{source:'demo',asOf:null,items:[
  {key:'mixed-scrap',label:'Mischschrott',unit:'EUR/t',price:null},
  {key:'grade-3',label:'Sorte 3',unit:'EUR/t',price:null},
  {key:'shredder-feed',label:'Schreddervormaterial',unit:'EUR/t',price:null},
  {key:'copper',label:'Kupfer',unit:'EUR/kg',price:null},
  {key:'brass',label:'Messing',unit:'EUR/kg',price:null},
  {key:'lead',label:'Blei',unit:'EUR/kg',price:null},
  {key:'zinc',label:'Zink',unit:'EUR/kg',price:null},
  {key:'aluminium',label:'Aluminium',unit:'EUR/kg',price:null},
  {key:'cable',label:'Kabel',unit:'EUR/kg',price:null},
  {key:'motors',label:'Elektromotoren',unit:'EUR/t',price:null},
  {key:'batteries',label:'Bleibatterien',unit:'EUR/t',price:null},
  {key:'stainless-v2a',label:'V2A Edelstahl',unit:'EUR/t',price:null},
  {key:'stainless-v4a',label:'V4A Edelstahl',unit:'EUR/t',price:null}
],note:'Tagespreise / Richtwerte. Händlerpreis kann abweichen.'}}}

class WerkZSimplePilotService{
  constructor({auth,entitlements,repository,storage,voice,mail,extractor,outbound,market,portfolio,scrapPrices,pickupDefaults={},clock=()=>new Date(),audit=()=>{}}){Object.assign(this,{auth,entitlements,repository,storage,voice,mail,extractor,outbound,market,portfolio,scrapPrices,clock,audit});this.pickupDefaults={vehicleCostPerKm:0.45,handlingCostEur:15,minimumProfitEur:50,targetMarginPct:15,vehiclePayloadKg:1200,...pickupDefaults}}
  session(token,cap='pilot.read'){const s=this.auth.resolveSession(req(token,'session'));this.entitlements.require(s.organisationId,'werkz.simple');if(!s.capabilities.includes(cap)&&!s.capabilities.includes('pilot.admin'))throw Object.assign(new Error('forbidden'),{code:'FORBIDDEN'});return s}
  event(s,type,id,payload={}){this.audit({organisationId:s.organisationId,actorId:s.actorId,eventType:type,entityType:'pilot',entityId:id,source:'werkz.simple',payload})}
  summary(token){const s=this.session(token),calls=this.repository.list(s.organisationId,'calls'),docs=this.repository.list(s.organisationId,'documents'),missing=this.missingDocumentsForSession(s);const m=this.clock().toISOString().slice(0,7);return {open:calls.filter(x=>x.status!=='erledigt').length,callbacks:calls.filter(x=>x.status==='neu'||x.status==='Rückruf').length,documentsThisMonth:docs.filter(x=>x.receivedAt.slice(0,7)===m).length,missingDocuments:missing.length}}
  async recordCall(token,input={}){const s=this.session(token,'pilot.write');const x=input.providerPayload?await this.voice.accept({payload:input.providerPayload}):input;const row=this.createInquiryRow(s.organisationId,x);this.repository.add('calls',row);this.event(s,'pilot.call.created',row.id,{source:row.source});return row}
  createInquiryRow(organisationId,x={}){return {id:uid('call'),organisationId:req(organisationId,'organisationId'),createdAt:this.clock().toISOString(),status:'neu',name:String(x.name||'Unbekannt').trim().slice(0,160),phone:String(x.phone||'').trim().slice(0,80),topic:String(x.topic||x.anliegen||'Rückruf').trim().slice(0,500),location:String(x.location||x.address||'').trim().slice(0,240),material:String(x.material||'').trim().slice(0,160),quantity:String(x.quantity||'').trim().slice(0,120),estimatedWeightKg:money(x.estimatedWeightKg),distanceKm:money(x.distanceKm),scheduledFor:x.scheduledFor||null,sourceNoteId:x.sourceNoteId||null,category:classifyInquiry(x),priority:'normal',source:x.source||'manual'}}
  publicInquiry(organisationId,input={}){if(input.company)throw Object.assign(new Error('spam denied'),{code:'SPAM_DENIED'});if(input.consent!==true)throw Object.assign(new Error('consent required'),{code:'VALIDATION_ERROR'});const clean={name:req(input.name,'name'),phone:req(input.phone,'phone'),topic:req(input.topic||input.reason,'topic'),location:String(input.location||input.address||'').trim(),material:String(input.material||'').trim(),quantity:String(input.quantity||'').trim(),source:'website-contact'};const row=this.createInquiryRow(organisationId,clean);this.repository.add('calls',row);this.audit({organisationId:row.organisationId,actorId:'public-website',eventType:'pilot.public-inquiry.created',entityType:'pilot',entityId:row.id,source:'werkz.simple',payload:{source:row.source}});return {id:row.id,status:row.status,received:true}}
  listCalls(token){const s=this.session(token);return this.repository.list(s.organisationId,'calls').sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
  addNote(token,text,clientMutationId=null){const s=this.session(token,'pilot.write'),mutationId=String(clientMutationId||'').trim().slice(0,160);if(mutationId){const existing=this.repository.list(s.organisationId,'notes').find(x=>x.clientMutationId===mutationId);if(existing){const workItem=this.repository.list(s.organisationId,'workItems').find(x=>x.sourceNoteId===existing.id)||null;return {...existing,workItem,replayed:true}}}const parsed=parseOperationalNote(text,this.clock()),row={id:uid('note'),organisationId:s.organisationId,createdAt:this.clock().toISOString(),clientMutationId:mutationId||null,text:parsed.raw,interpretation:{action:parsed.action,materialKey:parsed.materialKey,materialLabel:parsed.materialLabel,weightKg:parsed.weightKg,amountEur:parsed.amountEur,date:parsed.date,dealer:parsed.dealer,expectedCategory:parsed.expectedCategory}};this.repository.add('notes',row);let workItem=null;if(parsed.action!=='notiz'){workItem={id:uid('work'),organisationId:s.organisationId,createdAt:this.clock().toISOString(),source:'voice-note',sourceNoteId:row.id,action:parsed.action,status:parsed.documentExpected?'beleg-fehlt':'geplant',materialKey:parsed.materialKey,materialLabel:parsed.materialLabel,weightKg:parsed.weightKg,spokenAmountEur:parsed.amountEur,eventDate:parsed.date||this.clock().toISOString().slice(0,10),dealer:parsed.dealer,expectedCategory:parsed.expectedCategory,documentExpected:parsed.documentExpected,documentId:null,matchedAt:null,matchReason:null,originalText:parsed.raw};this.repository.add('workItems',workItem);if(parsed.action==='abholung-geplant'){const call=this.createInquiryRow(s.organisationId,{name:'Sprachnotiz',topic:'Abholung: '+parsed.raw,material:parsed.materialLabel,quantity:parsed.weightKg?parsed.weightKg+' kg':'',estimatedWeightKg:parsed.weightKg,scheduledFor:parsed.date,sourceNoteId:row.id,source:'voice-note'});this.repository.add('calls',call)}}this.event(s,'pilot.note.created',row.id,{action:parsed.action,documentExpected:parsed.documentExpected});return {...row,workItem}}
  missingDocumentsForSession(s){const today=this.clock().toISOString().slice(0,10);return this.repository.list(s.organisationId,'workItems').filter(x=>x.documentExpected===true&&!x.documentId&&(!x.eventDate||x.eventDate<=today)).sort((a,b)=>(a.eventDate||a.createdAt).localeCompare(b.eventDate||b.createdAt))}
  listMissingDocuments(token){const s=this.session(token);return this.missingDocumentsForSession(s)}
  listWorkItems(token){const s=this.session(token);return this.repository.list(s.organisationId,'workItems').sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
  linkDocumentToWorkItem(s,row,requestedId=null){const category=String(row.receiptCategory||'').toLowerCase(),date=String(row.date||row.receivedAt||'').slice(0,10);let item=null,reason='';if(requestedId){item=this.repository.find(s.organisationId,'workItems',String(requestedId));if(!item||item.documentExpected!==true||item.documentId)throw Object.assign(new Error('work item not available'),{code:'VALIDATION_ERROR'});reason='manuell aus Beleg-fehlt-Liste'}else{if(!category||category==='sonstiges'||category==='privat')return null;item=this.repository.list(s.organisationId,'workItems').filter(x=>x.documentExpected===true&&!x.documentId&&x.expectedCategory===category&&sameDayOrNear(x.eventDate,date)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];reason='Kategorie + Zeitraum'}if(!item)return null;const updated=this.repository.update(s.organisationId,'workItems',item.id,{documentId:row.id,status:'beleg-hochgeladen',matchedAt:this.clock().toISOString(),matchReason:reason});this.repository.update(s.organisationId,'documents',row.id,{linkedWorkItemId:item.id});return updated}
  async addDocument(token,input){const s=this.session(token,'pilot.write');this.entitlements.require(s.organisationId,'werkz.documents');const mutationId=String(input.clientMutationId||'').trim().slice(0,160);if(mutationId){const existing=this.repository.list(s.organisationId,'documents').find(x=>x.clientMutationId===mutationId);if(existing)return {...existing,replayed:true}}const bytes=Buffer.from(req(input.dataBase64,'dataBase64'),'base64'),id=uid('doc'),stored=this.storage.put({organisationId:s.organisationId,id,fileName:req(input.fileName,'fileName'),mime:req(input.mime,'mime'),bytes}),ex=await this.extractor.extract({fileName:input.fileName,mime:input.mime,bytes}),classification=classifyExpense(ex,input),row={id,organisationId:s.organisationId,receivedAt:this.clock().toISOString(),clientMutationId:mutationId||null,type:ex.type||'Sonstiges',company:ex.company||'',dealer:ex.dealer||ex.company||'',date:ex.date||null,amount:money(ex.amount),businessAmount:money(input.businessAmount??ex.businessAmount),receiptCategory:String(input.receiptCategory||'').toLowerCase()||null,expenseClass:classification.expenseClass,expenseReason:classification.expenseReason,weight:ex.weight??null,materialKey:ex.materialKey||'',material:ex.material||'',unit:ex.unit||null,unitPrice:money(ex.unitPrice),description:ex.description||'',storage:stored};this.repository.add('documents',row);const matchedWorkItem=this.linkDocumentToWorkItem(s,row,input.workItemId||null);if(matchedWorkItem)row.linkedWorkItemId=matchedWorkItem.id;if(row.type==='Wiegeschein'&&row.dealer&&row.material&&Number(row.weight)>0&&Number(row.amount)>0){this.addSettlementRow(s,{dealer:row.dealer,date:row.date||row.receivedAt.slice(0,10),materialKey:row.materialKey||row.material.toLowerCase().replace(/\s+/g,'-'),materialLabel:row.material,weightKg:Number(row.weight),totalEur:Number(row.amount),unit:row.unit||null,unitPrice:row.unitPrice,sourceDocumentId:id})}this.event(s,'pilot.document.created',id,{type:row.type,expenseClass:row.expenseClass});return row}
  classifyDocument(token,input={}){const s=this.session(token,'pilot.write'),id=req(input.documentId,'documentId'),expenseClass=req(input.expenseClass,'expenseClass').toLowerCase();if(!['betrieblich','privat','pruefen'].includes(expenseClass))throw Object.assign(new Error('expenseClass invalid'),{code:'VALIDATION_ERROR'});const patch={expenseClass,expenseReason:String(input.note||'manuell gewählt').slice(0,500)};if(input.businessAmount!=null)patch.businessAmount=money(input.businessAmount);const row=this.repository.update(s.organisationId,'documents',id,patch);if(!row)throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});this.event(s,'pilot.document.classified',id,{expenseClass});return row}
  listDocuments(token,m=null){const s=this.session(token),selected=m?month(m):null;return this.repository.list(s.organisationId,'documents').filter(x=>!selected||x.receivedAt.slice(0,7)===selected).sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt))}
  deleteDocument(token,id){const s=this.session(token,'pilot.write'),documentId=req(id,'documentId'),row=this.repository.find(s.organisationId,'documents',documentId);if(!row)throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});if(this.storage&&typeof this.storage.remove==='function')this.storage.remove({organisationId:s.organisationId,id:documentId,storage:row.storage});this.repository.removeWhere(s.organisationId,'settlements','sourceDocumentId',documentId);for(const item of this.repository.list(s.organisationId,'workItems').filter(x=>x.documentId===documentId))this.repository.update(s.organisationId,'workItems',item.id,{documentId:null,status:'beleg-fehlt',matchedAt:null,matchReason:null});this.repository.remove(s.organisationId,'documents',documentId);this.event(s,'pilot.document.deleted',documentId,{type:row.type,receiptCategory:row.receiptCategory||null});return {deleted:true,id:documentId}}
  documentFile(token,id){const s=this.session(token),documentId=req(id,'documentId'),row=this.repository.find(s.organisationId,'documents',documentId);if(!row)throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});if(!this.storage||typeof this.storage.read!=='function')throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});return {mime:row.storage&&row.storage.mime||'application/octet-stream',fileName:row.storage&&row.storage.fileName||'beleg',bytes:this.storage.read({organisationId:s.organisationId,id:documentId,fileName:row.storage&&row.storage.fileName})}}

  async pickupEstimate(token,input={}){const s=this.session(token,'pilot.write'),snap=await this.scrapPrices.snapshot({organisationId:s.organisationId}),items=Array.isArray(snap.items)?snap.items:[],materialKey=req(input.materialKey,'materialKey'),item=items.find(x=>x.key===materialKey);if(!item)throw Object.assign(new Error('material not found'),{code:'NOT_FOUND'});const weightKg=numeric(input.weightKg,'weightKg',{min:1,max:100000}),oneWayKm=numeric(input.distanceKm??0,'distanceKm',{min:0,max:2000}),roundTripKm=input.roundTripKm!=null?numeric(input.roundTripKm,'roundTripKm',{min:0,max:4000}):oneWayKm*2,vehicleCostPerKm=numeric(input.vehicleCostPerKm??this.pickupDefaults.vehicleCostPerKm,'vehicleCostPerKm',{min:0,max:10}),handlingCostEur=numeric(input.handlingCostEur??this.pickupDefaults.handlingCostEur,'handlingCostEur',{min:0,max:10000}),minimumProfitEur=numeric(input.minimumProfitEur??this.pickupDefaults.minimumProfitEur,'minimumProfitEur',{min:0,max:100000}),targetMarginPct=numeric(input.targetMarginPct??this.pickupDefaults.targetMarginPct,'targetMarginPct',{min:0,max:95}),payloadKg=numeric(input.vehiclePayloadKg??this.pickupDefaults.vehiclePayloadKg,'vehiclePayloadKg',{min:1,max:100000});const price=scrapMid(item);if(!Number.isFinite(price))throw Object.assign(new Error('price unavailable'),{code:'VALIDATION_ERROR'});const lo=Number.isFinite(Number(item.priceMin))?Number(item.priceMin):price,hi=Number.isFinite(Number(item.priceMax))?Number(item.priceMax):price,gross=money(scrapValue(item,weightKg,price)),grossLow=money(scrapValue(item,weightKg,lo)),grossHigh=money(scrapValue(item,weightKg,hi)),driveCost=money(roundTripKm*vehicleCostPerKm),netBeforePurchase=money(gross-driveCost-handlingCostEur),targetProfit=money(Math.max(minimumProfitEur,gross*targetMarginPct/100)),maxCustomerPayout=money(Math.max(0,netBeforePurchase-targetProfit)),customerPayout=input.customerPayoutEur==null?null:numeric(input.customerPayoutEur,'customerPayoutEur',{min:0,max:1000000}),expectedProfit=customerPayout==null?null:money(netBeforePurchase-customerPayout),decision=expectedProfit==null?(maxCustomerPayout>0?'lohnt':'knapp'):(expectedProfit>=targetProfit?'lohnt':expectedProfit>=0?'knapp':'nicht-lohnend'),row={id:uid('pickup'),organisationId:s.organisationId,createdAt:this.clock().toISOString(),materialKey,materialLabel:item.label,weightKg,price,displayUnit:item.unit==='EUR/t'?'€/t':'€/kg',gross,grossLow,grossHigh,distanceKm:oneWayKm,roundTripKm,vehicleCostPerKm,driveCost,handlingCostEur,targetProfit,maxCustomerPayout,customerPayoutEur:customerPayout,expectedProfit,vehiclePayloadKg:payloadKg,loadPct:money(weightKg/payloadKg*100),decision,priceSource:snap.source||'Richtwert',priceAsOf:snap.asOf||null};this.repository.add('pickupEstimates',row);this.event(s,'pilot.pickup.estimated',row.id,{materialKey,decision});return row}
  listPickupEstimates(token){const s=this.session(token);return this.repository.list(s.organisationId,'pickupEstimates').sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
  addSettlementRow(s,input={}){const unit=input.unit==='EUR/t'||input.unit==='EUR/kg'?input.unit:(Number(input.weightKg)>=100?'EUR/t':'EUR/kg'),weightKg=numeric(input.weightKg,'weightKg',{min:0.01,max:1000000}),totalEur=numeric(input.totalEur,'totalEur',{min:0,max:10000000}),derived=unit==='EUR/t'?totalEur/(weightKg/1000):totalEur/weightKg,row={id:uid('settlement'),organisationId:s.organisationId,createdAt:this.clock().toISOString(),date:String(input.date||this.clock().toISOString().slice(0,10)),dealer:req(input.dealer,'dealer').slice(0,160),materialKey:req(input.materialKey,'materialKey').slice(0,120),materialLabel:String(input.materialLabel||input.materialKey).slice(0,160),weightKg:money(weightKg),totalEur:money(totalEur),unit,unitPrice:money(input.unitPrice??derived),sourceDocumentId:input.sourceDocumentId||null,distanceKm:money(input.distanceKm)};this.repository.add('settlements',row);return row}
  recordSettlement(token,input={}){const s=this.session(token,'pilot.write'),row=this.addSettlementRow(s,input);this.event(s,'pilot.settlement.created',row.id,{dealer:row.dealer,materialKey:row.materialKey});return row}
  listSettlements(token){const s=this.session(token);return this.repository.list(s.organisationId,'settlements').sort((a,b)=>(b.date+b.createdAt).localeCompare(a.date+a.createdAt))}
  dealerInsights(token,materialKey=null){const s=this.session(token),rows=this.repository.list(s.organisationId,'settlements').filter(x=>!materialKey||x.materialKey===materialKey),groups=new Map();for(const row of rows){const key=row.dealer+'|'+row.materialKey;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row)}return [...groups.values()].map(list=>{list.sort((a,b)=>(b.date+b.createdAt).localeCompare(a.date+a.createdAt));const latest=list[0],avg=money(list.reduce((n,x)=>n+Number(x.unitPrice||0),0)/list.length);return {dealer:latest.dealer,materialKey:latest.materialKey,materialLabel:latest.materialLabel,unit:latest.unit,latestPrice:latest.unitPrice,latestDate:latest.date,averagePrice:avg,samples:list.length}}).sort((a,b)=>Number(b.latestPrice)-Number(a.latestPrice))}
  routePlan(token){const s=this.session(token),calls=this.repository.list(s.organisationId,'calls').filter(x=>x.category==='Abholung'&&x.status!=='erledigt'),voice=this.repository.list(s.organisationId,'workItems').filter(x=>x.action==='abholung-geplant'&&x.status==='geplant'&&!calls.some(c=>(x.sourceNoteId&&c.sourceNoteId===x.sourceNoteId)||(c.source==='voice-note'&&x.originalText&&String(c.topic||'').includes(x.originalText)))),stops=[...calls.map(x=>({id:x.id,name:x.name||'Abholung',location:x.location||'',material:x.material||'',quantity:x.quantity||'',estimatedWeightKg:x.estimatedWeightKg,distanceKm:x.distanceKm,phone:x.phone||'',scheduledFor:x.scheduledFor||null,source:x.source||'call',originalText:x.topic||''})),...voice.map(x=>({id:x.id,name:'Sprachauftrag',location:'',material:x.materialLabel||'',quantity:x.weightKg?x.weightKg+' kg':'',estimatedWeightKg:x.weightKg,distanceKm:null,phone:'',scheduledFor:x.eventDate||null,source:'voice-note',originalText:x.originalText||''}))].sort((a,b)=>String(a.scheduledFor||'9999-12-31').localeCompare(String(b.scheduledFor||'9999-12-31'))||(Number(a.distanceKm)||9999)-(Number(b.distanceKm)||9999));return {stops,estimatedWeightKg:money(stops.reduce((n,x)=>n+(Number(x.estimatedWeightKg)||0),0)),note:'Offene Aufträge aus Anrufen und Sprachnotizen. Routenoptimierung braucht später einen Karten-/Distanzanbieter.'}}
  async relevantMail(token){const s=this.session(token);this.entitlements.require(s.organisationId,'werkz.channel.gmail');return (await this.mail.listRelevant({organisationId:s.organisationId})).filter(x=>x.relevant!==false).map(x=>({...x,mutatesMailbox:false}))}
  prepareExport(token,m,selectedDocumentIds=null){const s=this.session(token,'pilot.write');this.entitlements.require(s.organisationId,'werkz.billing-prep');const selected=month(m),all=this.repository.list(s.organisationId,'documents').filter(x=>x.receivedAt.slice(0,7)===selected),requested=Array.isArray(selectedDocumentIds)?new Set(selectedDocumentIds.map(String)):null,docs=all.filter(x=>x.expenseClass!=='privat'&&(!requested||requested.has(x.id))),row={id:uid('export'),organisationId:s.organisationId,month:selected,createdAt:this.clock().toISOString(),status:'prepared',documentIds:docs.map(x=>x.id),count:docs.length,availableCount:all.length,privateExcludedCount:all.filter(x=>x.expenseClass==='privat').length,notSelectedCount:all.filter(x=>x.expenseClass!=='privat'&&requested&&!requested.has(x.id)).length,reviewCount:docs.filter(x=>x.expenseClass==='pruefen').length,totalAmount:Math.round(docs.reduce((n,x)=>n+(Number.isFinite(Number(x.businessAmount))?Number(x.businessAmount):(x.expenseClass==='betrieblich'?(Number(x.amount)||0):0)),0)*100)/100};return this.repository.add('exports',row)}
  async sendExport(token,{exportId,confirm,to}){const s=this.session(token,'pilot.write');if(confirm!==true)throw Object.assign(new Error('confirmation required'),{code:'CONFIRMATION_REQUIRED'});const row=this.repository.find(s.organisationId,'exports',req(exportId,'exportId'));if(!row)throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});const docs=this.repository.list(s.organisationId,'documents').filter(x=>row.documentIds.includes(x.id)),recipient=req(to,'to'),delivery=await this.outbound.send({organisationId:s.organisationId,to:recipient,subject:'Unterlagen '+row.month,text:'WerkZ Monatsübergabe',documents:docs}),createdAt=this.clock().toISOString(),archiveId=uid('archive');let stored={archiveId,fileCount:docs.length,manifestSha256:null,objectKey:null};if(this.storage&&typeof this.storage.archiveExport==='function')stored=this.storage.archiveExport({organisationId:s.organisationId,archiveId,exportRow:row,documents:docs,delivery:{...delivery,to:recipient},createdAt});const archive={id:archiveId,organisationId:s.organisationId,exportId:row.id,month:row.month,createdAt,documentIds:row.documentIds.slice(),count:docs.length,totalAmount:row.totalAmount,recipient,deliveryMode:delivery&&delivery.mode||null,deliveryAccepted:delivery&&delivery.accepted===true,manifestSha256:stored.manifestSha256||null,objectKey:stored.objectKey||null,status:'archived'};this.repository.add('archives',archive);this.repository.update(s.organisationId,'exports',row.id,{status:'handed-off',sentAt:createdAt,archiveId});this.event(s,'pilot.export.archived',archiveId,{month:row.month,count:docs.length});return {...row,status:'handed-off',sentAt:createdAt,archive,delivery}}
  listExportArchives(token){const s=this.session(token);return this.repository.list(s.organisationId,'archives').sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
  exportArchiveManifest(token,id){const s=this.session(token),archive=this.repository.find(s.organisationId,'archives',req(id,'archiveId'));if(!archive)throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});if(this.storage&&typeof this.storage.readArchiveManifest==='function')return this.storage.readArchiveManifest({organisationId:s.organisationId,archiveId:archive.id});return {...archive,files:[]}}
  exportArchiveFile(token,id,fileName){const s=this.session(token),archive=this.repository.find(s.organisationId,'archives',req(id,'archiveId'));if(!archive||!this.storage||typeof this.storage.readArchiveFile!=='function')throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});const manifest=this.storage.readArchiveManifest({organisationId:s.organisationId,archiveId:archive.id}),entry=manifest.files.find(x=>x.fileName===fileName);if(!entry)throw Object.assign(new Error('not found'),{code:'NOT_FOUND'});return {bytes:this.storage.readArchiveFile({organisationId:s.organisationId,archiveId:archive.id,fileName}),mime:entry.mime,fileName:entry.originalFileName||entry.fileName}}

  async marketSnapshot(token){const s=this.session(token);this.entitlements.require(s.organisationId,'werkz.crypto-monitor');const [market,portfolio]=await Promise.all([this.market.snapshot({organisationId:s.organisationId}),this.portfolio.portfolio({organisationId:s.organisationId})]);return {label:'Demo-Portfolio',readOnly:true,market,portfolio,generatedAt:this.clock().toISOString()}}
  async scrapPriceSnapshot(token){const s=this.session(token);const snap=await this.scrapPrices.snapshot({organisationId:s.organisationId});return {...snap,items:Array.isArray(snap.items)?snap.items.map(x=>({...x,displayUnit:x.unit==='EUR/t'?'€/t':'€/kg'})):[],generatedAt:this.clock().toISOString()}}
}

function cookieValue(cookie,name){const x=String(cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='));return x?decodeURIComponent(x.slice(name.length+1)):null}
function sendJson(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(data))}
async function readBody(reqr,limit=14*1024*1024){const chunks=[];let size=0;for await(const c of reqr){size+=c.length;if(size>limit)throw Object.assign(new Error('too large'),{code:'PAYLOAD_TOO_LARGE'});chunks.push(c)}const raw=Buffer.concat(chunks).toString('utf8');return raw?JSON.parse(raw):{}}
function status(error){return {UNAUTHENTICATED:401,FORBIDDEN:403,ENTITLEMENT_DENIED:403,NOT_FOUND:404,CONFIRMATION_REQUIRED:409,PAYLOAD_TOO_LARGE:413,VALIDATION_ERROR:400,SPAM_DENIED:400,RATE_LIMITED:429}[error.code]||500}
function createPilotHttpHandler({service,defaultTaxRecipient='steuerberater@example.invalid',publicOrganisationId='org-device-test'}){
  const recentPublic=new Map();
  function allowPublic(request){const ip=String(request.headers['x-forwarded-for']||request.socket?.remoteAddress||'unknown').split(',')[0].trim();const now=Date.now(),windowMs=10*60*1000,limit=8;const values=(recentPublic.get(ip)||[]).filter(x=>now-x<windowMs);if(values.length>=limit)throw Object.assign(new Error('rate limited'),{code:'RATE_LIMITED'});values.push(now);recentPublic.set(ip,values)}
  return async function(reqr,res){const url=new URL(reqr.url,'http://werkz.invalid');if(!url.pathname.startsWith('/pilot/api/')&&!url.pathname.startsWith('/pilot/public/'))return false;const token=cookieValue(reqr.headers.cookie,'werkz_session');try{
    if(reqr.method==='POST'&&url.pathname==='/pilot/public/contact'){allowPublic(reqr);const body=await readBody(reqr,64*1024);sendJson(res,201,service.publicInquiry(publicOrganisationId,body));return true;}
    if(reqr.method==='GET'&&url.pathname==='/pilot/api/summary')sendJson(res,200,service.summary(token));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/calls')sendJson(res,200,service.listCalls(token));
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/calls')sendJson(res,201,await service.recordCall(token,await readBody(reqr)));
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/notes'){const b=await readBody(reqr);sendJson(res,201,service.addNote(token,b.text,b.clientMutationId))}
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/missing-documents')sendJson(res,200,service.listMissingDocuments(token));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/work-items')sendJson(res,200,service.listWorkItems(token));
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/documents')sendJson(res,201,await service.addDocument(token,await readBody(reqr)));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/documents')sendJson(res,200,service.listDocuments(token,url.searchParams.get('month')||null));
    else if(reqr.method==='GET'&&url.pathname.startsWith('/pilot/api/documents/')&&url.pathname.endsWith('/file')){const id=decodeURIComponent(url.pathname.slice('/pilot/api/documents/'.length,-'/file'.length));const file=service.documentFile(token,id);res.writeHead(200,{'content-type':file.mime,'content-disposition':'inline; filename="'+String(file.fileName).replace(/"/g,'')+'"','cache-control':'private, max-age=60','x-content-type-options':'nosniff'});res.end(file.bytes)}
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/documents/classify')sendJson(res,200,service.classifyDocument(token,await readBody(reqr)));
    else if(reqr.method==='DELETE'&&url.pathname.startsWith('/pilot/api/documents/'))sendJson(res,200,service.deleteDocument(token,decodeURIComponent(url.pathname.slice('/pilot/api/documents/'.length))));
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/pickup-estimates')sendJson(res,201,await service.pickupEstimate(token,await readBody(reqr)));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/pickup-estimates')sendJson(res,200,service.listPickupEstimates(token));
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/settlements')sendJson(res,201,service.recordSettlement(token,await readBody(reqr)));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/settlements')sendJson(res,200,service.listSettlements(token));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/dealer-insights')sendJson(res,200,service.dealerInsights(token,url.searchParams.get('material')||null));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/route-plan')sendJson(res,200,service.routePlan(token));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/mail')sendJson(res,200,await service.relevantMail(token));
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/export/prepare'){const b=await readBody(reqr);sendJson(res,201,service.prepareExport(token,b.month,b.selectedDocumentIds))}
    else if(reqr.method==='POST'&&url.pathname==='/pilot/api/export/send'){const b=await readBody(reqr);sendJson(res,200,await service.sendExport(token,{...b,to:b.to||defaultTaxRecipient}))}
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/export-archives')sendJson(res,200,service.listExportArchives(token));
    else if(reqr.method==='GET'&&url.pathname.startsWith('/pilot/api/export-archives/')&&url.pathname.endsWith('/manifest')){const id=decodeURIComponent(url.pathname.slice('/pilot/api/export-archives/'.length,-'/manifest'.length));sendJson(res,200,service.exportArchiveManifest(token,id))}
    else if(reqr.method==='GET'&&url.pathname.startsWith('/pilot/api/export-archives/')&&url.pathname.includes('/file/')){const rest=url.pathname.slice('/pilot/api/export-archives/'.length),cut=rest.indexOf('/file/'),id=decodeURIComponent(rest.slice(0,cut)),name=decodeURIComponent(rest.slice(cut+6)),file=service.exportArchiveFile(token,id,name);res.writeHead(200,{'content-type':file.mime,'content-disposition':'attachment; filename="'+String(file.fileName).replace(/"/g,'')+'"','cache-control':'private, no-store','x-content-type-options':'nosniff'});res.end(file.bytes)}

    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/market')sendJson(res,200,await service.marketSnapshot(token));
    else if(reqr.method==='GET'&&url.pathname==='/pilot/api/scrap-prices')sendJson(res,200,await service.scrapPriceSnapshot(token));
    else sendJson(res,404,{error:'NOT_FOUND'});
    return true
  }catch(e){sendJson(res,status(e),{error:e.code||'ERROR',message:e.code==='VALIDATION_ERROR'?e.message:'Request failed'});return true}}
}

function parseSnapshot(value){if(!value)return {};try{const x=JSON.parse(value);return x&&typeof x==='object'?x:{}}catch{return {}}}
function createPilotRuntime({auth,entitlements,dataDir,audit=()=>{}}){const snap=parseSnapshot(process.env.WERKZ_DEMO_CRYPTO_SNAPSHOT),scrap=parseSnapshot(process.env.WERKZ_SCRAP_PRICE_SNAPSHOT),pickupDefaults=parseSnapshot(process.env.WERKZ_PICKUP_DEFAULTS);return new WerkZSimplePilotService({auth,entitlements,repository:new FilePilotRepository(path.join(dataDir,'pilot.json')),storage:new PilotDocumentStorage(path.join(dataDir,'documents')),voice:new FakeVoiceProvider(),mail:new FakeMailProvider(),extractor:new FakeExtractor(),outbound:new DraftMailProvider(),market:new StaticMarketProvider(snap.market||null),portfolio:new StaticPortfolioProvider(snap.portfolio||null),scrapPrices:new StaticScrapPriceProvider(scrap.items?scrap:null),pickupDefaults,audit})}

module.exports={VoiceProviderPort,MailProviderPort,DocumentExtractionPort,OutboundMailPort,MarketDataPort,PortfolioReadPort,ScrapPricePort,FilePilotRepository,MemoryPilotRepository,PilotDocumentStorage,FakeVoiceProvider,FakeMailProvider,FakeExtractor,DraftMailProvider,StaticMarketProvider,StaticPortfolioProvider,StaticScrapPriceProvider,WerkZSimplePilotService,createPilotHttpHandler,createPilotRuntime,parseSnapshot,classifyInquiry,classifyExpense,parseOperationalNote};
